### ISSUE TITLE
I encountered a problem when writing a smart contract

### ISSUE THREAD

**Issue by riven-blade** [anza-xyz/agave#1125]
#### Problem

v1.18.12

    Program Ca6omQmJ5z2ykKhmJKTWs3tj5XEj6wwvEquHFHhyD3X9 failed: Access violation in unknown section at address 0xffffffffffffffff of size 32

**Comment by riven-blade** [comment]
I checked the code and the permissions of my account, and found no problems. I didn’t have any clues from the source code, so I could only ask the community for help.

**Comment by anthontaylor** [comment]
I run into this issue as well when I compile my program with anything greater than 1.18.0. Just tried it with the newest version and still encounter the issue.
