### ISSUE TITLE
solana-account-decoder out dated dependency

### ISSUE THREAD

**Issue by ghost** [anza-xyz/agave#1266]
#### Problem
mismatch between solana-account-decoder from anza-xyz/agave and solana-account-decoder crate (v1.18.12), while the 1.18.12 github relies on spl-token-2022 v=2.0.1, the solana-account-decoder crate (https://crates.io/crates/solana-account-decoder/1.18.12) relies on spl-token-2022 v1.0.0, which itself relies on solana-zk-token-sdk v1.17.6 which relies on solana-program v1.17.6

+ i believe there is the exact same issue in solana-transaction-status crate

#### Proposed Solution
replace spl-token-2022 v1.0.0 dep by v2.0.1 in solana-account-decoder-crate

**Comment by joncinque** [comment]
Thanks for your report. The SPL crates almost always use an older version of solana-program, and while it does create some tricky situations, it's workable.

What do you mean exactly by the dependency on token-2022 v2.0.1? 1.18.12 on Github depends on v1.0.0: https://github.com/anza-xyz/agave/blob/be4a6720efedbd0bd2472ee6818a2c55bd5df89b/Cargo.toml#L396, just like what you see on crates.io.

And master depends on 3.02 https://github.com/anza-xyz/agave/blob/d36954cb72679dbe130f4a0a212b8c8a0026ea78/Cargo.toml#L403

Are you having a particular build issue? Or do you have an example that doesn't work?

**Comment by ghost** [comment]
I ignored the SPL always use an older version of solana-program, why is that?
no then if this is intended behavior i have nothing to report.
thanks for the fast answer.

**Comment by joncinque** [comment]
SPL has to use a published version of solana-program, so it'll typically use the newest available version. So let's say master is on 1.18, and hasn't been published. This means SPL uses 1.17, the newest published version. When we cut the branch for 1.18 and publish the crates, they will use SPL, which uses 1.17. We don't upgrade SPL crates on 1.18 unless necessary. So we'll always have this off-by-one situation.

**Comment by ghost** [comment]
this makes sense, ty for explaining!
