### ISSUE TITLE
Solana wallet connection issue when initialize the transactions via Frontend

### ISSUE THREAD

**Issue by blockchain-app12** [anza-xyz/agave#128]
Hi Team,
Hereby sharing the set of codes and console of the error log, please clarify it will more helpful. I working all of the scenarios and modules, it is perfectly working in solana localnet with the Frontend, while we change the network to devnet, the following errors occurs when try to connect the phantom wallet with the functions.

My question : Is there any issue on devnet with phantom wallet provider, because solana localnet is working properly.
Please let us know to proceed further.

![solana devenet try](https://github.com/anza-xyz/agave/assets/48212011/be8079fb-b689-472c-997a-ca69c35a5325)
![solana localnet try](https://github.com/anza-xyz/agave/assets/48212011/33b01adf-9a95-45cd-98b9-0a6612ff5b56)
![solana error console](https://github.com/anza-xyz/agave/assets/48212011/ffc2f83e-f8d9-4757-aec8-bb8cc87e7c72)

**Comment by CriesofCarrots** [comment]
We don't offer developer or wallet support here.
