### ISSUE TITLE
The solana-web3.js confirmTransaction function with "confirmed" is stuck when transaction had been finalized 

### ISSUE THREAD

**Issue by wngasinur** [anza-xyz/agave#1338]
#### Problem

I'm getting random issue while calling `confirmTransaction`

```
// send transaction with "confirmed" blockhash

// transaction seems to be finalized before below line is being executed

connection.confirmTransaction(
{
    blockhash: latestBlockValue.blockhash,
    lastValidBlockHeight: latestBlockValue.lastValidBlockHeight,
    signature: finalSignature,
},  "confirmed")
```

The confirmTransaction never returns and it is throwing block height expiry exception. Is this expected behaviour ?

**Comment by CriesofCarrots** [comment]
solana-web3.js is not a part of this repository. Please report any bugs there: https://github.com/solana-labs/solana-web3.js
Or if you'd like to ask and discuss development questions, please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
