### ISSUE TITLE
the incremental folder is not cleaned up and grows 1000% while the snap is made.

### ISSUE THREAD

**Issue by iammelea** [anza-xyz/agave#1563]
Hi Solan@s
While creating a new snap, incremental ones are not made. This is ok.
Depending on the validator configuration, the default creation of a snap is every 12k slots = around every 3 hours and lasts half an hour.

The problem is that while no incremental is created during this half hour that the snap creation lasts, the incremental folder starts to grow to more than 40GB in that half hour.
Then, after the snap is created and the first incremental for that snap is made, the size of the incremental folder becomes stable again until the creation of the next snap begins and the folder grows again over 40GB.

The solution would be that while the snap is being created and new incremental are not made, the incremental folder does not grow more than what it normally needs, around 10GB and not +40Gb.

Here are some results of the script I wrote to capture where the excess storage was. As you can see, it is normal for the snap folder to grow 100% when creating the other snap, but it is not normal for the incremental folder to grow 1000% during this moment too.

```
incremental folder Fri May 31 14:44:40 UTC 2024
44G	/mnt/soldisk/inc_snaps
40	/mnt/soldisk/inc_snaps/remote
incremental-snapshot-269025974-269051552-4oJEXWfXGjz6V2cSaLfHG8mQSL5dV4jUfXMmWErGqjvv.tar.zst  remote  snapshot
snap folder
143G	/mnt/soldiskb/snapsMB
snapshot-269025974-9u7puB8w97d9edf8UqBWgTZvFVrL15gD1MhryEwDgZtU.tar.zst  tmp-snapshot-archive-269051656-ZAPAjz  tmp-snapshot-archive-269051656.tar.zst
```
then after the snap is made

```
incremental folder Fri May 31 14:47:00 UTC 2024
4.3G	/mnt/soldisk/inc_snaps
40	/mnt/soldisk/inc_snaps/remote
incremental-snapshot-269051656-269055541-Hn6K8dam4wvT7166688dkriUDJiboQBsS9454ESjHbfQ.tar.zst  remote  snapshot
snap folder
73G	/mnt/soldiskb/snapsMB
snapshot-269051656-GLADZGajspVkjMvC9cJhnmExXgW34G1Ej8cCXAfk54cS.tar.zst
```
Solana Jito `v1.18.14`

Thanks

**Comment by brooksprumo** [comment]
Ah, I see. We are putting the serialized bank snapshot inside the incremental snapshot archives directory. 

In v1.18, we serialize the bank and make the bank snapshot in the AccountsBackgroundService thread. The archiving happens later in the SnapshotPackagerService. And SPS is also where we purge old bank snapshots. So while SPS is archiving snapshots, ABS will be snapshotting and serializing banks. If SPS is archiving a full snapshot, ABS will take snapshots at the incremental snapshot interval, which is often much faster. This leads to many bank snapshots getting taken in ABS that get purged once SPS finish the full snapshot archive and begins working on the next highest snapshot archive.

If the incremental snapshot archives dir is on a ram-backed FS, this will likely cause big RAM spikes while SPS is archiving a full snapshot.

We should allow specifying all the snapshot directories separately: full snapshot archive, incremental snapshot archive, bank snapshot.

**Comment by brooksprumo** [comment]
Note, in master (soon to be v2.0), snapshotting and serializing banks has been moved to SPS. This means we will *not* be piling up many serialized bank snapshots waiting for SPS.

**Comment by iammelea** [comment]
yeah, this
*We should allow specifying all the snapshot directories separately: full snapshot archive, incremental snapshot archive, bank snapshot.*

Now this snapshot folder is more bank-snapshot, but is running on the incremental folder.
The thing is worsted if changing the default snap and incremental creation. for example
setup snaps each 100K slots instead of the 25k default and incremental each 200, but the incremental no was happening each 200 slots and also was a bunch slots behind the tip, so the incremental was like +600 slots behind instead of 200 slots or so.
then, the snapshot folder inside incrementals was growing crazy. meanwhile snaps happening each 100k slots.

meanwhile running all this test, I just realized we are missing the ability to start a node with one snapshot + incremental, but without creating snapshots or incrementals.

because, If I'm running different setups, nodes, RPC, relayers, I mean several differents servers, think why want to create snapshots in all the nodes? 
Also in the validator node. If I could do it right now, I would run my validator without creating snaps, but with the ability to get them from any of my private RPC servers after some restart in case.
also a good utility for the backup node, create snaps meanwhile the validator not.

 This can be done or the snapshot creation is vital for the software to keep running?
If can be done, this can solve some resources things. imo
