### ISSUE TITLE
catchup 900 slots take +25 Minutes. & incremental creation every 200 slots are creating incremental far behind 

### ISSUE THREAD

**Issue by iammelea** [anza-xyz/agave#1627]
hey @brooksprumo one hug!

*For "restart is slow and catching up is also slow", what specifically does that mean? From what starting time/point to what ending time/point?*

Restart, open ledger and start catching up take 5minutes

![Screenshot from 2024-06-06 11-49-59](https://github.com/anza-xyz/agave/assets/38863192/45c74a1b-d070-435b-bd86-15e0e12abbae)

`v1.18.15`
catchup 900 slots take +25 Minutes. 
I think the problem is probably? : Node is creating snaps and incremental but still not catching up. and if run snaps and incremental out ram, then is very slow the snap creation and the catching up process. 

We are currently experiencing ram problems and the Anza team recommends that we remove everything related to accounts from the ram, and run it on disks, when making this change the validator takes around 30 minutes to synchronize 900 slots.

Here 
```
Thu Jun  6 10:11:27 UTC 2024
⠐ 931 slot(s) behind (us:270200945 them:270201876), our node is gaining at 2.0 slots/second (AVG: 4.9 slots/second, ETA: slot 270202299 in 3m 10s)
```
Then
```
9U4WqNGVywKt3gG9HSt9tGVXBDXJvgid6BVweRysaJmg has caught up (us:270204016 them:270204023)
Thu Jun  6 10:27:41 UTC 2024
```
Furthermore, the incremental ones are being created very late, think the snaps and incremental ones should start to be made when the node is synchronized, not while it is trying to reach the network tip.

```
incremental-snapshot-270161079-270186902-DoZUPt9EvD5UVMSQw6ykn13ycHs7Ltxmot6CpZn2Rdzp.tar.zst 
snapshot                              
tmp-snapshot-archive-270203619.tar.zst
incremental-snapshot-270187111-270203418-Bkt2qv4x2WvicQGnMrGtUQQ7JXvEXmciwGScKTg4oXn9.tar.zst  
tmp-snapshot-archive-270203619-IAnTbi
```
Also, when everything is normally working, I have noticed that the incrementals are being created very late, so this delays, even more, when you do a restart, I have changed my configuration to create the incrementals every 100 as default instead of every 200 to see if more are made on time and not about 300-400 slots behind the tip.

thanks

**Comment by cielu** [comment]
Hello, can you share your configuration information and the command running on the node?

**Comment by cielu** [comment]
When I was using v1.18.15, I found that the response to the RPC request was very slow.

**Comment by iammelea** [comment]
after some tests today setup, results in restart and catch up  the tip in 12 minutes.
closing this

**Comment by iammelea** [comment]
after some tests today with different(s) setup, results in restart and catch up the tip in 12 minutes.
closing this
