### ISSUE TITLE
getsignaturesforaddress should give a parameter like after #35576

### ISSUE THREAD

**Issue by ItsFunny** [anza-xyz/agave#1629]
I want to fetch the address all transaction history and store it into my database , It is better if we can get the signature from earliest to latest,not from latest to earliest

**Comment by ItsFunny** [comment]
@buffalojoec  halo,can you help support this?

**Comment by buffalojoec** [comment]
Hey @ItsFunny, sorry but it's likely going to be a non-starter for changing the order of transactions returned by `getSignaturesForAddress`. Not only does this require extra work for the RPC to reverse the response, but we'd also have to change up the `before` and `until` fields of this method's parameters.

There's really no reason your application can't reverse the order on its own.

**Comment by ItsFunny** [comment]
thanks for you reply @buffalojoec  
Yeah, I can reverse the order on my own , But what if i want to to sync the latest as well .
I have a app to sync the address all transaction history, and I don't want to do it by analyze every block  
So for now ,this is my simple way:
I have two functions , the first is sync_latest ,the second is sync_previous 
sync_latest: 
1. get last synced signature **LATEST** as until parameter 
2. loop execute getSignaturesForAddress until **LATEST**,When I process a limit length of data I save the **EARLIEST** signature to the database for the sync_previous to sync the previous records ,Because during the sync it will failed for some network issue or database issue ... ,If I restart without duplicate check it will cost a lot 

sync before:
get the sync_latest **EARLIEST**  try to sync the previous records 

It is a bit weird because there are no such rpc to help me restore the data from earliest to latest and keep synced all the time , if have, all I do is just save the latest signature per limit records and next time I can continue to catch up to the latest using the value I saved last time ,no need to worry about network issue or anything else because it is one way street

**Comment by buffalojoec** [comment]
> It is a bit weird because there are no such rpc to help me restore the data from earliest to latest and keep synced all the time , if have, all I do is just save the latest signature per limit records and next time I can continue to catch up to the latest using the value I saved last time ,no need to worry about network issue or anything else because it is one way street

Yeah, I think you'll have to sync all the transactions initially, and then when you need to sync newer transactions you'd just use the last synced signatures for the `until` parameter. You should only have to call again if there's been >1000 transactions since last sync.
