### ISSUE TITLE
`test_add_builtin_account` test is flaky

### ISSUE THREAD

**Issue by jstarry** [anza-xyz/agave#1696]
#### Problem
https://buildkite.com/anza/agave/builds/5840#01900827-c057-4097-b27d-796d0052dd5f

The last assertion in `test_add_builtin_account` failed:
```rust
        // No replacement should have happened
        assert_eq!(bank.get_account_modified_slot(&program_id).unwrap().1, slot);
 ```

**Comment by jstarry** [comment]
So, new builtin accounts are created with `rent epoch == 0` because `INITIAL_RENT_EPOCH == 0` and this function is used in `add_builtin_account`:

```rust
    fn inherit_specially_retained_account_fields(
        &self,
        old_account: &Option<AccountSharedData>,
    ) -> InheritableAccountFields {
        const RENT_UNADJUSTED_INITIAL_BALANCE: u64 = 1;

        (
            old_account
                .as_ref()
                .map(|a| a.lamports())
                .unwrap_or(RENT_UNADJUSTED_INITIAL_BALANCE),
            old_account
                .as_ref()
                .map(|a| a.rent_epoch())
                .unwrap_or(INITIAL_RENT_EPOCH),
        )
    }
```

The reason this test is flaky is that sometimes the test builtin account gets rent collected in a partitioned rent pass and despite skip rewrites being enabled, we don't skip rewrites if the account in question has a rent epoch of 0:
    
```rust
    fn skip_rewrite(rent_amount: u64, account: &AccountSharedData) -> bool {
        // if rent was != 0
        // or special case for default rent value
        // these cannot be skipped and must be written
        rent_amount == 0 && account.rent_epoch() != 0
    }
```
    
cc @brooksprumo @jeffwashington, can one of you fix the test?

**Comment by brooksprumo** [comment]
> cc @brooksprumo @jeffwashington, can one of you fix the test?

Sure thing. https://github.com/anza-xyz/agave/pull/1727

**Comment by jstarry** [comment]
Btw I think it make more sense for builtins to be added with the `RENT_EXEMPT_RENT_EPOCH` but probably not important to fix because we are unlikely to add more builtins

**Comment by brooksprumo** [comment]
Yeah. We also have similar issues for sysvars, where they are created with a rent epoch of zero. IIRC, those ones do get updated currently. But once we turn of rent collection, they may never get touched again, And thus any new sysvars could get created with a value of `0` instead of `MAX`. Likely something we need to address as well.
