### ISSUE TITLE
Unexpected SWQoS behavior with `--use-rpc`

### ISSUE THREAD

**Issue by jacobcreech** [anza-xyz/agave#1752]
#### Problem
`--use-rpc` flag doesn't seem to do what it is expected to do. Testing it out on mainnet-beta results in longer times for deployment than without it. All test results were with a hello world program that consisted of 194 transactions to deploy. Tests were run with Triton RPC with SWQoS forwarding enabled.

With `—use-rpc`
| Microlamports per CU paid | Time to deploy |
|------------|---------------------------------------------------------------------------------------------|
| 8k | 1:01:15.20 |
| 100k | 54:24.73 |
| 100k | 50:08.12 |
| 100k | 42:45.98 |
| 100k | 43:49.45 |
| 500k | 41:59.93 |

Without `—use-rpc`
| Microlamports per CU paid | Time to deploy |
|------------|---------------------------------------------------------------------------------------------|
| 8k | 26:51.28 |
| 10k | 24:04.20 |
| 100k | 29:31.04 |

Median priority fees of recent blocks were under the fees paid for each at the time of deployment. The expectation is that if you're deploying a program using `--use-rpc` with a RPC that is paired with a validator with stake via SWQoS, the deployment would be faster than just spamming the TPU ports of the leaders.

**Comment by bw-solana** [comment]
CC @ilya-bobyr

**Comment by illia-bobyr** [comment]
Just to clarify, `1:01:15.20` - this is 1 hour to run `194` transactions, correct?
Or are you deploying multiple instances of this program?

**Comment by jacobcreech** [comment]
> Just to clarify, 1:01:15.20 - this is 1 hour to run 194 transactions, correct?
Or are you deploying multiple instances of this program?

That was a single program deployment that took over an hour. 

I'm not convinced this is not related to something at the infra-level depending on what RPC you're using. I ran with Helius and got the following:

with `--use-rpc`
| Microlamports per CU paid | Time to deploy |
| - | - |
| 500k | 13.385 |
| 100k | 23.531 |

without `--use-rpc`
| Microlamports per CU paid | Time to deploy |
| - | - |
| 100k | 28:44.65 |

I'll do some more investigation and close this if it ends up just infra-related.

**Comment by jacobcreech** [comment]
I worked with the rpc provider and was able to determine there was an issue forwarding txs with their infra. I was able to then get sub 30s deploys with their infra.

I'm going to close this issue as it seems to work as intended and the unexpected behavior was due to an infra issue.
