### ISSUE TITLE
After upgrading to V1.18.15, it takes a long time to respond to requests for data information

### ISSUE THREAD

**Issue by cielu** [anza-xyz/agave#1766]
Problem

I upgraded my rpc node to v1.18.15 today, and the synchronization has been completed. However, when I request: getTransaction, the response is very slow and it takes 5sec ~ 20 seconds to wait.

This problem seems to occur only in non-full nodes, and the signature requested was a long time ago. It should return null, but it has been responding.

Proposed Solution

response null:

{"jsonrpc":"2.0","result": null,"id":1}

**Comment by cielu** [comment]
<img width="1433" alt="image" src="https://github.com/anza-xyz/agave/assets/13715811/10d2e4f6-b344-4521-84e2-edeab0492389">

The first request is for historical data from a long time ago, and the second request is for the most recent signature.

**Comment by avinashbo** [comment]
@cielu Is there any associated spike in CPU usage noticed? I am looking at a similar problem

**Comment by cielu** [comment]
@avinashbo  There should be some impact, but I'm not sure. My CPU is EPYC 7502, which is only 2.5GHz. I think this is a problem. We are preparing to replace this server, but we don't know what configuration is more suitable. We have already changed and configured multiple servers, and I feel that the read and write speed of Nvme can't keep up.

**Comment by cielu** [comment]
@avinashbo  But I think there must be something wrong with this v1.18.15 version, because I don't have these problems when I use v1.17.34, but the synchronization speed is not that fast

**Comment by brooksprumo** [comment]
v1.18 is now obsolete. Please open a new issue if the problem persists. Please also know that the agave repository's issue tracker is not for node operator support.
