### ISSUE TITLE
solana-type-overrides is causing dependency bloat

### ISSUE THREAD

**Issue by kevinheavey** [anza-xyz/agave#1775]
#### Problem
`solana-type-overrides` was added to multiple crates in #1634 

The following crates do not use `futures` but because they depend on `solana-type-overrides` they now depend on `futures`:

- solana-program-runtime
- solana-bpf-loader-program
- solana-loader-v4-program
- solana-stake-program
- solana-system-program
- solana-svm

#### Proposed Solution
Move solana_type_overrides::executor to a new crate

**Comment by LucasSte** [comment]
> Move solana_type_overrides::executor to a new crate

Instead of creating a new crate, we can mark `futures` as an optional decency and put the executor module behind a cfg feature. This way, crates that need the module import `type_overrides` with the feature enabled and the dependency is only built when necessary.

**Comment by kevinheavey** [comment]
Crates are friendlier to parallel builds and have fewer footguns like failing to check a feature in CI
