### ISSUE TITLE
error: package solana-program v2.0.0 cannot be built because it

### ISSUE THREAD

**Issue by MaeThird** [anza-xyz/agave#1826]
#### Problem
use solana-program = "2.0.0" to compile a very simple custom program failed with `package solana-program v2.0.0 cannot be built because it requires rustc 1.75.0 or newer, while the currently active rustc version is 1.72.0-dev`
the output of **cargo-build-sbf --version** is `solana-cargo-build-sbf 1.18.5  platform-tools v1.39  rustc 1.72.0`

I mean where i can find the toolchain supporting rustc 1.75.0 or above for now?

**Comment by lingcoder** [comment]
I encountered the same problem, it was a mess

**Comment by Nagaprasadvr** [comment]
try rustup update
