### ISSUE TITLE
Flaky Test: solana-cli::stake test_stake_redelegation

### ISSUE THREAD

**Issue by anza-team** [anza-xyz/agave#1916]
_AUTO-GENERATED. DO NOT EDIT._

[📝 Buildkite Analytics](https://buildkite.com/organizations/anza/analytics/suites/agave/tests/018d9c41-ebcf-775f-a7b1-100aa7b3cf71)

**Comment by joncinque** [comment]
Test was removed with https://github.com/anza-xyz/agave/pull/2213
