### ISSUE TITLE
Feature Gate: Enable ZK ElGamal Proof program

### ISSUE THREAD

**Issue by samkim-crypto** [anza-xyz/agave#1966]
### SIMD

https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/0153-elgamal-proof-program.md

### Description

Enable the native ZK ElGamal Proof program

### Feature ID

zkhiy5oLowR7HY4zogXjCjeMXyruLqBwSWH21qcFtnv

### Activation Method

Single Core Contributor

### Deployment Considerations

Make sure that the compute units assigned to each of the proof instructions are suitable.

### Minimum Beta Version

2.0.0

### Minimum Stable Version

2.0.0

**Comment by willhickey** [comment]
Tracking this activation on another issue now:
https://github.com/orgs/anza-xyz/projects/9/views/1?pane=issue&itemId=73058762&issue=anza-xyz%7Cfeature-gate-tracker%7C26
