### ISSUE TITLE
Add priority fees and retry count to `solana program deploy`

### ISSUE THREAD

**Issue by jacobcreech** [anza-xyz/agave#21]
#### Problem
With higher usage on the cluster, transactions are requiring the need of a priority fee to be set in order to give them a greater chance of landing. This makes deploying programs, which require a larger amount of transactions than normal usage, to often fail before the program is finished deploying.

#### Proposed Solution
Add two new features:
- Ability to set priority fee when using `solana program deploy`
- Ability to set custom retry count

**Comment by Nagaprasadvr** [comment]
Can I work on this ?

**Comment by CriesofCarrots** [comment]
> Can I work on this ?

You don't need to ask to work on an issue. PRs are always welcome. Feel free to ask clarifying or implementation questions, though.
