### ISSUE TITLE
error: Invalid value for '--tvu-receive-threads <NUMBER>': input '8' out of range 1..=2

### ISSUE THREAD

**Issue by adborden** [anza-xyz/agave#2103]
#### Problem

I'm in the process of switching from solana-validator to agave-validator but it refuses to start with the error:

> error: Invalid value for '--tvu-receive-threads <NUMBER>': input '8' out of range 1..=2

The `--tvu-receive-threads` option doesn't appear in the `--help`, so it's unclear how this value should be set or what its behavior is.

Just a hunch, but I suspect it's because the vm has only 2 vCPUs. This is in a test environment I use prior to being run on testnet. I use this to test my playbooks. The purpose is to check that the validator is installed and can startup successfully, it doesn't need to run well.

```
$ /opt/solana-v2.0.2/bin/agave-validator  --version
agave-validator 2.0.2 (src:b5bc3b23; feat:4288794394, client:Agave)

$ nproc
2
```

Startup options:
```
exec /opt/solana-v2.0.2/bin/agave-validator \
  --identity /home/sol/keypairs/validator-identity-keypair.json \
  --vote-account /home/sol/keypairs/validator-vote-account-keypair.json \
  --known-validator dv1ZAGvdsz5hHLwWXsVnM94hWf1pjbKVau1QVkaMJ92 \
  --known-validator dv2eQHeP4RFrJZ6UeiZWoc3XTtmtZCUKxxCApCDcRNV \
  --known-validator dv4ACNkpYPcE3aKmYDqZm9G5EB3J4MRoeE7WNDRBVJB \
  --known-validator dv3qDFk1DTF36Z62bNvrCXe9sKATA6xvVy6A798xxAS \
  --entrypoint entrypoint.devnet.solana.com:8001 \
  --entrypoint entrypoint2.devnet.solana.com:8001 \
  --entrypoint entrypoint3.devnet.solana.com:8001 \
  --entrypoint entrypoint4.devnet.solana.com:8001 \
  --entrypoint entrypoint5.devnet.solana.com:8001 \
  --expected-genesis-hash EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG \
  --ledger /home/sol/ledger \
  --accounts /home/sol/accounts \
  --dynamic-port-range 8000-8020 \
  --limit-ledger-size \
  --log /var/log/solana/validator.log \
  --only-known-rpc \
  --private-rpc \
  --rpc-port 8899 \
  --wal-recovery-mode skip_any_corrupted_record \
  --no-port-check
```

Specifying `--tvu-receive-threads 2` allows the validator to startup correctly in this case.

#### Proposed Solution

- Include `--tvu-receive-threads` in the docs
- Use a fixed default and range for the option inclusive of the default so that the validator can startup

**Comment by steviez** [comment]
> Include --tvu-receive-threads in the docs

This argument is hidden on purpose at the moment; it is not publicly supported and subject to change.

> I suspect it's because the vm has only 2 vCPUs

Yeah, exactly. The flag was added in https://github.com/anza-xyz/agave/pull/550. The number of threads used to be hard-coded to 8 deeper in the codebase; it is now configurable through this hidden CLI flag (which may be made visible / officially supported in the future) with a default value of 8.

The logic for the range of allowed value is defined in this trait:
https://github.com/anza-xyz/agave/blob/87a1295bb950c0ca8d4184ac01dab02d2d6869f1/validator/src/cli/thread_args.rs#L86-L100

So, the range of allowed thread is `[1, 2]` on your machine. But, as mentioned, the default of 8 (which matched pre-existing behavior) is in conflict with this comment:
https://github.com/anza-xyz/agave/blob/87a1295bb950c0ca8d4184ac01dab02d2d6869f1/validator/src/cli/thread_args.rs#L94

That comment is true, and for a real validators is valid so I'm hesitant to lift the better error checking. Arguably, the max function could do `max(get_max_thread_count(), Self::default())` to avoid the error in your scenario. Will think about this one a bit more and respond back / link any PR's I make. For now, you have your workaround which will continue to work for any `2.x` release
