### ISSUE TITLE
Linux ARM64 binary releases

### ISSUE THREAD

**Issue by jalaziz** [anza-xyz/agave#2124]
#### Problem

Today, there are only x86_64 releases for Linux. However, ARM releases are available for macOS (darwin). It would be great if Linux arm64 releases could be made available.

#### Proposed Solution

Add Linux arm64 builds to the release pipeline.

**Comment by dzmitry-lahoda** [comment]
assuming duplicate of https://github.com/anza-xyz/agave/issues/1734

**Comment by joncinque** [comment]
Correct, this is a duplicate, thanks!
