### ISSUE TITLE
solana transfer can't retrieve SOL from a mint address, even if fee payer is different

### ISSUE THREAD

**Issue by SolBugz** [anza-xyz/agave#2134]
#### Problem

Create a new fungible mint. Send some SOL to the mint address (and be prepared to lose it!). You can't use "solana transfer" to retrieve it, regardless of what fee payer account you specify. Is this somehow illegal under the protocol? If so, then it would be nice to have a warning somewhere in the docs, or in real time "I noticed you're trying to fund a mint address, which is a black hole..."

#### Proposed Solution

I'm sure you can think of some better behavior, if only to document this in the right place. Or fix it if it's really a bug.

**Comment by SolBugz** [comment]
@joncinque I think this is worth more investigation because my Stack Exchange question was never answered. In any event, the error message is something about an instruction failing, with no annotation about it being illegal to transfer funds out of a wallet which happens to double as a mint address.

**Comment by joncinque** [comment]
This is part of the protocol: https://solana.com/docs/core/accounts#key-points

> Every account has a program "owner". Only the program that owns an account can modify its data or deduct its lamport balance. However, anyone can increase the balance.

Your Stack Exchange will eventually get answered with some more info, or you can read through some documentation about how the protocol works.
