### ISSUE TITLE
spl-token set-transfer-fee has different granularity than spl-token create-token

### ISSUE THREAD

**Issue by SolBugz** [anza-xyz/agave#2135]
#### Problem

set-transfer-fee works in whole tokens. create-token with "--transfer-fee" works in 10^(-decimals) tokens.

#### Proposed Solution

Either make them equal or document this more clearly. The way things are now is just asking for errors.

**Comment by joncinque** [comment]
Thanks for the report! This is the incorrect repo, so I've created an issue at https://github.com/solana-labs/solana-program-library/issues/7020 to track this
