### ISSUE TITLE
BankingStage: Gossip votes held

### ISSUE THREAD

**Issue by apfitzge** [anza-xyz/agave#2183]
#### Problem
Migrating issue from https://github.com/solana-labs/solana/issues/34973

- Gossip votes are held in `ClusterInfoVoteListener` until we become leader.
- This seems unneccessary now since both voting threads insert into a shared data-structure which only keeps the latest vote.
- Holding the votes can lead to misleading metrics since tpu votes are a sustained throughput, whereas gossip votes come in nearly all at once

#### Proposed Solution
- `ClusterInfoVoteListener` just verifies the votes and sends to BankingStage for it to handle

**Comment by apfitzge** [comment]
@carllin @AshwinSekar - I migrated this issue. My understanding from previous issue is it is not necessary for us to continue doing this holding.

@carllin if that is not the case, please let us know.

**Comment by AshwinSekar** [comment]
Confirmed with carl in April that votes do not need to be held in `ClusterInfoVoteListener` with the caveat that banking stage only drains the votes for slots on the `working_bank`'s fork and leaves the remaining untouched.

The benefit of holding votes in `ClusterInfoVoteListener` is that if the leader decides to build it's first block off of fork1 and it's second block off of fork2, gossip votes for fork2 will still make it into the second block, even if they are filtered out for the first block.

Essentially we want to move this check:
https://github.com/anza-xyz/agave/blob/a2eaf6d189a4316c6f5ef8d9508dc628c7548e7b/core/src/verified_vote_packets.rs#L89-L90

Into here:
https://github.com/anza-xyz/agave/blob/a2eaf6d189a4316c6f5ef8d9508dc628c7548e7b/core/src/banking_stage/latest_unprocessed_votes.rs#L322-L323
