### ISSUE TITLE
BUILT_IN_INSTRUCTION_COSTS: ahash

### ISSUE THREAD

**Issue by apfitzge** [anza-xyz/agave#2196]
### Problem
- `BUILT_IN_INSTRUCTION_COSTS` using default hashing function
- Default hash function is slow

### Solution
- make `BUILT_IN_INSTRUCTION_COSTS` use `ahash`

**Comment by apfitzge** [comment]
@tao-stones I know you were moving things around w/ this map; will hold off making the change so I don't step on your toes.

**Comment by tao-stones** [comment]
> @tao-stones I know you were moving things around w/ this map; will hold off making the change so I don't step on your toes.

Would be good to hold off changes to this map, currently this map is small and static, so changing to `ahash` doesn't seem to be a priority. I think this map needs overhaul to meet two requirements: 
1. static default cost is per instruction, not per program_id
2. when new builtin programs, or new instructions, are created, there should be a way to ensure this map is updated, ideally automatically at compile time.

**Comment by apfitzge** [comment]
The map is small and static, but every transaction we ingest will check all top-level program keys against it. If we're ingesting 50ktps, then this means we could be doing a few hundred thousand checks against this map to compute the budget(s). If we can make the hashing of those keys ~4x faster then it seems like a simple win to me.

We could always explore completely different structs that does no hashing 😉

**Comment by tao-stones** [comment]
I'm under impression that with size of about a dozen, ahash probably don't have performance advantage over hash when do lookup. But I might be wrong, bench can tell 😃 But in anycase, don't think ahash would hurt anyway

**Comment by apfitzge** [comment]
My concern here has nothing to do with the size of the map, but with the number of keys we're checking if exist in the map, since whenver we check if the kye is in the map we must hash that key.
