### ISSUE TITLE
Curves syscall: EdwardPoint and RistrettoPoint compression

### ISSUE THREAD

**Issue by zfedoran** [anza-xyz/agave#2275]
#### Problem
It would be nice to be able to decompress pubkeys to curve points within the Solana SVM runtime.

The Edward curve syscalls already provide the computation required to `decompress()` a standard public key to an `EdwardsPoint`. However, this computation is [discarded](https://github.com/anza-xyz/agave/blob/c5b3e003345e5fa86f7bdf5fd819df2636e059e3/curves/curve25519/src/edwards.rs#L76-L77) and only a boolean value is returned to the caller.

#### Context
With feature gate [7rcw5UtqgDTBBv2EcynNfYckgdAaH1MAsCjKgXMkN7Ri](https://explorer.solana.com/address/7rcw5UtqgDTBBv2EcynNfYckgdAaH1MAsCjKgXMkN7Ri), the curve25519 group ops and validation [syscalls](https://github.com/anza-xyz/agave/blob/master/curves/curve25519/src/curve_syscall_traits.rs) were rolled out. These syscalls offer a ton of potential but are not usable with standard pubkeys as specified by [RFC 8032](https://datatracker.ietf.org/doc/html/rfc8032#section-5.1.3). 
#### Proposed Solution

It would be nice to offer a different syscall to compress/decompress pubkey slices ~~or to change the implementation so that the validate function also returns the EdwardsPoint itself~~.

cc @samkim-crypto @cavemanloverboy

**Comment by zfedoran** [comment]
Having had some time to dive deeper on this, it seems that the crux of the issue is in defining what `compress` and `decompress` would look like at the syscall level. Specifically, the uncompressed ed25519_dalek `EdwardPoint`/`RistrettoPoint` struct's don't have a direct serialization, instead, they use `compress()` [internally](https://github.com/dalek-cryptography/curve25519-dalek/blob/35e78b21efb61a1de148cbcf4cfe2c3d559fbec0/curve25519-dalek/src/edwards.rs#L265-L277). This was probably done to ensure FieldElement could be of variable type internally. 

Perhaps we could assume FieldElement51 and serialize to `[u32; 5]` or `[u64; 5]`. Also, it is not clear to me if returning a ed25519_dalek type is preferred over a generic POD type.

I'd love feedback on what the preferred approach would be.

**Comment by samkim-crypto** [comment]
What you pointed out is correct. There are multiple representation of decompressed curve points and conversions between the representations are generally done on-the-fly when different ops are applied to them.

The curve25519 syscalls were designed to work with the compressed (i.e. POD) types. The syscalls for add, subtract, multiply, etc. all take in pod types, decompresses them, applies the relevant ops, and then compresses them again. Except for advanced zk applications, these ops should be sufficient for most standard cryptographic applications (sig verification, vrf, etc.). It is unclear to me what the additional `decompress()` operation could provide.

**Comment by tsleesg** [comment]
@samkim-crypto 
Sounds like Code are working on an advanced Zero-Knowledge (ZK) feature in their new protocol - as you pointed out, some protocols might require working with uncompressed point representations for computations or proofs.

Other benefits for the general population - custom cryptographic protocols, better interoperability, audit/debugging.

Perhaps a solution is to:
1. Define compress() to return a fixed-size byte array ([u8; 32] for compressed form).
2. Define two versions of decompress():
 a. One that returns the appropriate ed25519_dalek type (EdwardPoint or RistrettoPoint).
 b. Another that returns a generic POD type (e.g. a struct containing the coordinates).

NB it's easier to get from u8 to u32 or u64 and you'd worry less about endianness.

**Comment by zfedoran** [comment]
@samkim-crypto Thanks for the context, I appreciate it. I agree that it makes sense to use the compressed representation as the default. 

It might be helpful to walk through an example use-case. As you've mentioned, one potential use case is that of `sig verification`. So lets take a look at what that might look like.

Lets assume I have a dynamically generated message that I want to verify inside an instruction. In this case, the use of the [native ed25519 pre-compute](https://docs.solanalabs.com/runtime/programs#ed25519-program) instruction is out of the question (it requires the message, pubkey, and signature to be hard-coded).

I think what you're saying is that instead of using the dalek_curve25519 library directly, I should instead use your curves library and let the compress/decompress actions happen internally (automatically).

**Comment by zfedoran** [comment]
Okay, it's a bit clunky but works.

```rust
        let message: &[u8]   = b"hello world";
        let pubkey: [u8; 32] = [ 
            73, 73, 170, 112, 75, 235, 154, 81, 203, 8, 44, 245, 233, 18, 204, 136, 
            162, 9, 233, 49, 154, 201, 171, 175, 47, 6, 223, 101, 105, 80, 95, 166
        ];
        let sig: [u8; 64] = [ 
            164, 121, 89, 242, 88, 29, 80, 177, 104, 20, 102, 176, 48, 133, 68, 8, 
            105, 33, 58, 86, 28, 108, 198, 140, 160, 219, 62, 184, 154, 181, 140, 33, 
            35, 102, 183, 203, 111, 33, 55, 170, 180, 138, 92, 196, 185, 201, 122, 167, 
            15, 112, 9, 228, 226, 112, 111, 10, 142, 73, 85, 43, 81, 152, 204, 13 
        ];

        // Normally, we could verify the signature using the Solana SDK 
        // (This is not SVM compatible; expensive internally)
        let sdk_sig = solana_sdk::signature::Signature::from(sig);
        assert!(sdk_sig.verify(&pubkey, &message));

        // Instead, lets verify the signature "by hand" using the new edward curve syscalls
        let pubkey_point = PodEdwardsPoint(pubkey);
        let neg_one = PodScalar((-Scalar::one()).to_bytes());
        
        let mut sig_lower: [u8; 32] = [0u8; 32];
        let mut sig_upper: [u8; 32] = [0u8; 32];
        sig_lower.copy_from_slice(&sig[..32]);
        sig_upper.copy_from_slice(&sig[32..]);

        let sig_R = PodEdwardsPoint(sig_lower);
        let sig_s: Scalar;
        if sig[31] & 240 == 0 {
            sig_s = Scalar::from_bits(sig_upper)
        } else {
            sig_s = Scalar::from_canonical_bytes(sig_upper).unwrap();
        }

        /*
        // todo... 
        if signature_R.is_small_order() || pubkey_point.is_small_order() {
            panic!("Signature verification failed: small order point");
        }
        */

        let mut h: Sha512 = Sha512::new();
        h.update(sig_R.0);
        h.update(&pubkey);
        h.update(&message);

        let f = h.finalize();
        let k = Scalar::from_bytes_mod_order_wide(f.as_ref());
        let minus_A = multiply_edwards(&neg_one, &pubkey_point).unwrap();

        let k_bytes = k.to_bytes();
        let minus_A_bytes = minus_A.0;
        let sig_s_bytes = sig_s.to_bytes();
        let g_bytes = G.compress().to_bytes(); // basepoint, could technically be precomputed

        let a = PodScalar(k_bytes);
        let A = PodEdwardsPoint(minus_A_bytes);
        let b = PodScalar(sig_s_bytes);
        let B = PodEdwardsPoint(g_bytes);

        // R = aA + bB
        // R = (k * minus_A) + (sig_s * G)

        let aA = multiply_edwards(&a, &A).unwrap();
        let bB = multiply_edwards(&b, &B).unwrap();
        let R = add_edwards(&aA, &bB).unwrap();

        let lhs = R.0;
        let rhs = sig_R.0;

        println!("{:?}", lhs);
        println!("{:?}", rhs);

        assert!(lhs == rhs);
```

@samkim-crypto given that I don't see a path forward with serializing uncompressed points, I'm going to close this (unless anyone has objections). 

Both you and @cavemanloverboy cleared a lot up for me; much appreciated!
