### ISSUE TITLE
The validator scan-for-incorrect-shred-version logic has issues

### ISSUE THREAD

**Issue by steviez** [anza-xyz/agave#2380]
#### Problem
The `backup_and_clear_blockstore()` method that a validator may call at startup has several flaws. A much lengthier description is provided later, but the issues are:
1. Only 80% of the cluster (by stake) must participate in a cluster restart. By participating in cluster restart, the blockstore cleanup is guaranteed to happen. For the other 20% of stake, this cleanup occurring is dependent on validators supplying the correct args after the fact.
2. As written, the blockstore scan that checks if there is cleanup necessary will run for 60s before timing out. This step is critical in cluster restarts, but could ideally be avoided for "regular" validators restarts (ie when an operator upgrades software versions) to minimize downtime.

<details>
<summary>Additional context about cluster restarts and blockstore cleaning</summary>

##### Cluster Restarts
A typical cluster involves the following:
- Choosing a slot `RESTART_SLOT` to restart at (typically the latest optimistically confirmed slot that contains at least one non-vote tx)
- Validators creating a snapshot at `RESTART_SLOT` with `ledger-tool create-snapshot RESTART_SLOT --hard-fork RESTART_SLOT ...` 
- Validators restartand supplying `--expected-shred-version`, `--wait-for-supermajority RESTART_SLOT`, and `--expected-bank-hash RESTART_SLOT_BANK_HASH` args to their validator

When `RESTART_SLOT` is chosen, it is almost always the case that leaders continue to create blocks with slot `> RESTART_SLOT`. That is, leaders continue to produce blocks even though the cluster fails to confirm/finalize those blocks. Given that `RESTART_SLOT` is chosen, any of these blocks for slot `> RESTART_SLOT` are to be considered invalid. We are able to detect and cleanup this state by the following means:
- When validators create the restart snapshot, they supply `--hard-fork RESTART_SLOT`. The `shred_version` that gets encoded in shreds is derived from the hard forks array stored in a `Bank`, and the addition of a new hard fork will change the shred version
    - Let `OLD_SV` be the old shred version and `NEW_SV` the new shred version
- When validators restart with the aforementioned cluster restart arguments, the following block is entered that will scan the blockstore and purge any shreds with slot `> RESTART_SLOT` and `shred_version != NEW_SV`
    - The implication here is that there could be shreds in the Blockstore with slot `> RESTART_SLOT` with `shred_version == OLD_SV`

https://github.com/anza-xyz/agave/blob/6e067fcd28620a32eab8461ad5e5be79e28d41f7/core/src/validator.rs#L600-L614

The cluster restarts when 80% of the cluster is in the wait-for-supermajority loop; this means that 80% will have supplied the necessary arguments to enter the loop (and cleanup the stale blockstore state).

The described workflow works for the 80%; however, the other 20% is where problems arise. In a perfect world, all validator operators would supply these new args to ensure their blockstores are properly cleaned. However, an inattentive operator may restart their node at a later time without the cluster restart args (ie just download snapshot from cluster). Without those args, the cleanup logic will not be run and the result is that the stale state may cause problems for that validator.

One more unfortunate piece is that validators who perform regular restarts on their node (non-cluster-restart such as for a software upgrade) might leave those cluster restart parameters in place. Leaving those parameters in place means the node will perform that scan at startup, which will timeout after 60s. The 60s scan means more time unnecessarily offline which is obviously non-ideal:
https://github.com/anza-xyz/agave/blob/6e067fcd28620a32eab8461ad5e5be79e28d41f7/core/src/validator.rs#L2184-L2191

</details>

#### Proposed Solution
1. The blockstore scan currently only occurs when the `--wait-for-supermajority` and `--expected-shred-version` arguments were supplied. We could instead move the blockstore scan to occur AFTER unpacking the snapshot; we can determine the shred version after the `Bank` is rebuilt by reading out the hard forks.
2. This part is tricky. An obvious case is`root_bank.slot() == wait_for_supermajority_slot` (assuming a WFSM slot was set). However, that is essentially the existing behavior we already have. We're more interested in being able to programmatically determine when we need to run the scan and/or making the scan faster. More thought will be needed for this aspect, but a few ideas to start out:
    - Check only the first shred in each slot, instead of every shred. I'll probably do this anyways and I'll go into more detail in that PR on why this is valid
    - Check slots in parallel; we're still early in startup so contention for CPU time shouldn't be awful
    - Check to see if the latest (or any really) hard fork lies within the min & max blockstore slots. If so, that tells us that a restart happened "recently" and it could be worthwhile to look. On the other hand, if the oldest blockstore slot is newer than the latest hard fork, we might be in the clear to skip the scan
    - Always perform the scan starting from root bank slot. Assuming default snapshot config, this would mean only scanning several 100 slots which should go pretty quick, especially in light of the other optimizations I mentioned above

**Comment by steviez** [comment]
@AshwinSekar - Finally got around to writing this up, feel free to weigh in as we had talked about this / I know you had thought about it a bit

**Comment by AshwinSekar** [comment]
I agree with the analysis here. I suggest we perform the scan right after loading blockstore here:
https://github.com/anza-xyz/agave/blob/f11b777e9bbbfdaa6550003ebe36c37331acd037/core/src/validator.rs#L740-L743
At this point we have an up to date `root` from `bank_forks` which takes care of any `hard_forks` or other artificial root situations.
We also have the "correct" shred version (more on this later) as computed from the genesis and `hard_forks`. 

> Check only the first shred in each slot, instead of every shred
> Check slots in parallel

I am in favor of this approach. The idea behind the `shred_version` scan is to avoid scenarios where we have old blocks that could lead to duplicate block scenarios such as voting using `bank_hash` computed from these old blocks. By only checking the first shred of each slot we run the risk of having a block with mixed `shred_version`s that goes unnoticed. 

However I don't believe this is possible. As this scan is performed before new post-restart shreds can be inserted, the first available shred is either:
* old shred version - it is safe to purge the entire slot as new shreds could not have been inserted yet
* new shred version - there is no possibility of an old shred being mixed in, as this means there has already been a previous restart where the purge would have ran.

**Comment by AshwinSekar** [comment]
As a side note, there is some cleanup we can do regarding the `expected_shred_version` as well as the `shred_version` ingested through gossip via the entrypoint.

Gossip will always connect using the shred version via the entrypoint, regardless of any cli flag:
https://github.com/anza-xyz/agave/blob/f11b777e9bbbfdaa6550003ebe36c37331acd037/gossip/src/cluster_info.rs#L3204-L3207
https://github.com/anza-xyz/agave/blob/f11b777e9bbbfdaa6550003ebe36c37331acd037/gossip/src/cluster_info.rs#L1782-L1796

For the initial backup and clear we use the gossip shred version if the cli flag is not set. Otherwise we proceed with the cli flag:
https://github.com/anza-xyz/agave/blob/5769cc1792b3c00b28dd04807243a12a8543286b/validator/src/main.rs#L1128-L1130
https://github.com/anza-xyz/agave/blob/f11b777e9bbbfdaa6550003ebe36c37331acd037/core/src/validator.rs#L595-L598 

And finally after loading blockstore we set the `shred_version` to what is computed from `hard_forks`:
https://github.com/anza-xyz/agave/blob/f11b777e9bbbfdaa6550003ebe36c37331acd037/core/src/validator.rs#L740-L743

So it is possible that the user supplies `shred_version_1` through the CLI and:
1) Gossip connects using `shred_version_2` from entrypoint
2) Initial `backup_and_clear` is performed using `shred_version_1`
3) Waiting for supermajority is done through gossip `shred_version_2`
4) Once blockstore is loaded the shred version is computed to be `shred_version_2` matching gossip
5) Node then panics as `shred_version_2` is not equal to `shred_version_1`: https://github.com/anza-xyz/agave/blob/f11b777e9bbbfdaa6550003ebe36c37331acd037/core/src/validator.rs#L747-L750

I think we should at least perform the comparison earlier so that operators that pass incorrect flags do not `backup_and_clear` the wrong shreds, and do not have to wait for WFSM to conclude in order to panic.

**Comment by steviez** [comment]
> Gossip will always connect using the shred version via the entrypoint, regardless of any cli flag:

I took another look and believe this to be incorrect.

We create the `Node` here; this has an uninitialized `shred_version` as you pointed out:
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/validator/src/main.rs#L1965
The `Node` is then passed to `Validator::new()`:
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/validator/src/main.rs#L2041-L2042
Within `Validator::new()`, we set the shred version based on the computed version, which is determined form `HardForks` that we pull out of rebuilt `Bank`:
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/core/src/validator.rs#L744-L747
`ClusterInfo` then gets a clone of `ContactInfo` (recalling that `node.info` has the shred version set):
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/core/src/validator.rs#L762-L766
We create a `GossipService` with `ClusterInfo` as a parameter:
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/core/src/validator.rs#L1146-L1154
`GossipService` spins up a `ClusterInfo::gossip()` thread:
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/gossip/src/gossip_service.rs#L81-L84
We hit the line to call `process_entrypoints()`:
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/gossip/src/cluster_info.rs#L1911
We check if `my_shred_version() == 0` and if so, fetch shred version from entrypoints:
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/gossip/src/cluster_info.rs#L1763
`my_shred_version()` accesses the shred version from `ContactInfo`; this value was set in `core/src/validator.rs`:
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/gossip/src/cluster_info.rs#L729-L731

I recently spun up a node with `--expected-shred-version` set and do NOT see the `Setting shred version to ...` log line from `process_entrypoints()` that you linked above.

**Comment by steviez** [comment]
> I agree with the analysis here. I suggest we perform the scan right after loading blockstore here:
> ...
> We also have the "correct" shred version (more on this later) as computed from the genesis and hard_forks
> ...
> I think we should at least perform the comparison earlier so that operators that pass incorrect flags do not backup_and_clear the wrong shreds, and do not have to wait for WFSM to conclude in order to panic.

I spliced three of your comments together here that are related. I agree with moving the `backup_and_clear()` call to after we have rebuilt `Bank` + compared `expected_shred_version` to `computed_shred_version`. Several points about this:
1. We will be able to error out if `expected != computed`
2. We will always have `computed`, so we no longer need to do `if let Some(expected_shred_version) = ...`

We're on the same page on all the major details, so going to start making some of these changes and we can hash out any remaining minor details in the individual PR's

**Comment by AshwinSekar** [comment]
> I recently spun up a node with --expected-shred-version set and do NOT see the Setting shred version to ... log line from process_entrypoints() that you linked above.

Good catch, I missed that `GossipService` was started with the cloned `ContactInfo`.

I checked the other `GossipService` for bootstrap and it respects the flag as well, so I think we can ignore my concern
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/validator/src/main.rs#L2012-L2014
https://github.com/anza-xyz/agave/blob/3ca67197c5cd142e355f0ad4263e6dd63d63f224/validator/src/bootstrap.rs#L155

**Comment by steviez** [comment]
A note for myself as I implement this. The current order of operations is:
1. Blockstore bad-shred-scan
2. Record highest slot in `Blockstore` for `halt_at_slot` in `ProcessOptions`
3. Rebuild initial bank

When we move current 1. after current 3. (so we can get hard-forks from Bank to calculate shred version), we would be recording `halt_at_slot` before potential purge. As such, the highest recorded slot could be a slot that is later purged. I think this is fine because if the `halt_at_slot` is just used to ensure that new slots to be processed are `<= halt_at_slot`. But, it would be more proper to record the actual value after `backup_and_clear_blockstore()`

OR, even better would be to actually do https://github.com/solana-labs/solana/issues/25577 so that we can split `ProcessOptions` up a bit (ie things that pertain to bank rebuild vs. block replay). Currently, the fact that we either rebuild from a snapshot OR start from genesis + replay slot 0 forces us to pass this struct all the time
