### ISSUE TITLE
Circular dependency check in CI is wrong about dev-dependencies

### ISSUE THREAD

**Issue by kevinheavey** [anza-xyz/agave#2428]
#### Problem
It's fine to have apparent circular dependencies if they're just dev-dependencies [UPDATE: they must also be path dependencies], but order-crates-for-publishing.py will still fail in this case. ~Unfortunately `cargo metadata` doesn't yet have a way to ignore dev-dependencies: https://github.com/rust-lang/cargo/issues/10718~

#### Proposed Solution
~I'll open this one up to the floor, but I see the Python script has a `dependency['kind'] == 'dev'` check in there - maybe we can just use this check to filter out all dev deps?~
Filter out path dev-dependencies in order-crates-for-publishing.py

**Comment by kevinheavey** [comment]
I assumed circular dev deps were fine because `cargo test` is fine with them but looks like `cargo publish` is not fine with them? https://github.com/rust-lang/cargo/issues/4242

**Comment by kevinheavey** [comment]
More investigation reveals that `cargo publish` is fine with circular dev deps if those dev deps are path dependencies

Example repo here: https://github.com/kevinheavey/circular-dev-dep

**Comment by joncinque** [comment]
Was this addressed with #2578?

**Comment by kevinheavey** [comment]
Yes
