### ISSUE TITLE
Fix CPU usage issue

### ISSUE THREAD

**Issue by diplodoq** [anza-xyz/agave#2677]
#### Problem
I have 2 x Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
64Gb DDR4, 
NVMe 1Tb, 
800Mbit Bandwidth

It's been running good without skips on 2.0.5, but after upgrade to 2.0.6 it doesn't work at all. Rebuilting storage and then crash.

**Comment by diplodoq** [comment]
I went back to 2.0.5, now everything works fine, but during the day it didn't work - solana catchup didn't go.

please fix 2.0.6, DO NOT RELEASE 2.0.6 to master as "minimum required", without fixing CPU issues.

**Comment by ksolana** [comment]
is this still an issue?

**Comment by steviez** [comment]
Closing this issue out because:
- We do validator support in our Discord (https://discord.com/invite/solana)
- There is insufficient information in this post (which cluster / nature of the crash / ...)
- Even for testnet, your node is under provisioned
