### ISSUE TITLE
Possible invalid result in alt_bn128 syscalls

### ISSUE THREAD

**Issue by 0x0ece** [anza-xyz/agave#268]
#### Problem

Looking at the code, I found the following a bit suspicious. When a function returns an error, the syscall returns success. Is this intended or a copy&paste error?

Examples:
https://github.com/anza-xyz/agave/blob/v1.18.6/programs/bpf_loader/src/syscalls/mod.rs#L1558-L1567
https://github.com/anza-xyz/agave/blob/v1.18.6/programs/bpf_loader/src/syscalls/mod.rs#L1806-L1808

#### Proposed Solution

Replace `Ok(..)` with `Err(..)`

**Comment by ripatel-fd** [comment]
@0x0ece I think this is intended. If you return `Err(SyscallError::{...})` that's considered a fatal error that aborts the VM.
But an invalid curve point should not abort the VM. It should gracefully return the error to the user.
