### ISSUE TITLE
Dependency Upgrade - curve25519-dalek

### ISSUE THREAD

**Issue by omkarshanbhag** [anza-xyz/agave#2690]
#### Problem
solana-program currently uses curve `curve25519-dalek` [v3.2.1](https://crates.io/crates/curve25519-dalek/3.2.1). It's [dependencies list](https://crates.io/crates/curve25519-dalek/3.2.1/dependencies) specifies zeroize `>=1, <1.4` which is pretty old and restrictive -- causes sub-dependency versions to not have overlap in crates that already depend on zeroize, among others. 

#### Proposed Solution
Upgrade to the latest version of `curve25519-dalek` [v4.1.3](https://crates.io/crates/curve25519-dalek/4.1.3/dependencies) which is must more permissive as the version of zeroize required is just `^1`

**Comment by steviez** [comment]
Hi @omkarshanbhag - this is already on our radar; we had updated but then had to back that change out. Given that is a known issue that is already being worked on, I'm going to close this issue but feel free to subscribe to https://github.com/anza-xyz/agave/pull/2252 to follow along
