### ISSUE TITLE
solana_download_utils] downloaded 362522728 bytes 0.4% 790656.2 bytes/s

### ISSUE THREAD

**Issue by cielu** [anza-xyz/agave#2809]
I don't know why, but my solana-validator is downloading snapshots very slowly, as if it only found 3RPCs. My previous node was 1.18.20, and then I saw it upgraded to 1.18.22, so I upgraded it, but it didn't download the snapshot overnight. And I wanted to switch back to 1.18.20 to download the snapshot, but it was still very slow. I used to download the snapshot in just 20 minutes, so I don't understand what's going on now.

**Comment by CriesofCarrots** [comment]
Sorry, we don't provide technical support on github. You can try the validator support and discussion channels [on discord](https://solana.com/discord).
If you subsequently discover a concrete bug in the Agave validator software, please do come back and report it here.
