### ISSUE TITLE
Keypair Generated with Passphrase is Not Recoverable Using solana-keygen recover Command

### ISSUE THREAD

**Issue by harsi-dhaliwal** [anza-xyz/agave#2825]
#### Problem
When generating a new keypair with `solana-keygen new -o ~/test-solana.json` ,
the resulting seed phrase and the used passphrase do not reproduce the same public key
when using the `solana-keygen recover "prompt://?key=0/0" -o ~/test-solana.json` for the same passphrase and seed phrase

#### Proposed Solution
Ensure consistency by using the same functions in both the new and recover commands for deriving the keypair from the seed phrase and passphrase combination. Specifically, the new command should use the same key derivation method as the [recover](https://github.com/solana-labs/solana/blob/master/keygen/src/keygen.rs#L528) command, instead of relying on the [Seed](https://github.com/solana-labs/solana/blob/master/keygen/src/keygen.rs#L494) struct from the bip39 crate.

**Comment by diman-io** [comment]
The `prompt` is required if you created the keypair with `--derivation-path`
