### ISSUE TITLE
solana-test-validator error, expects GNU-tar: proposed solution!

### ISSUE THREAD

**Issue by abhijayrajvansh** [anza-xyz/agave#2838]
## Problem

running `solana-test-validator` on macOS (with apple silicon or arm64) fails with the following error:

```bash
Ledger location: test-ledger
Log: test-ledger/validator.log
Error: failed to start validator: Failed to create ledger at test-ledger: io error: Error checking to unpack genesis archive: Archive error: extra entry found: "._genesis.bin" Regular
```

**reason**: the GNU `tar` program is not compatible with the BSD `tar` program that comes pre-installed.
and hence we were using: [gnu tar installation in .travis.yml](https://github.com/solana-labs/solana/blob/master/.travis.yml#L32)

```yml
- brew install gnu-tar
- PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
```

and here's the problem: this (`/usr/local/opt/gnu-tar/libexec/gnubin`) executable path is only valid for Intel-based macs (x86_64) and not for macs with apple silicon (arm64) chipset. by default, on apple silicon macs, executables are stored in a different location.

### less ideal solution:

a local fix: Install the gnu tar program using brew and export its executable path in your `.zshrc` file.

#### macOS with apple silicon (arm64):

```bash
brew install gnu-tar
# Put this in ~/.zshrc
export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
```

#### intel-based macOS (x86_64):

```bash
brew install gnu-tar
# Put this in ~/.zshrc
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
```

### Ideal Solution:

We can differentiate between Intel-based and Apple Silicon-based macOS directly in the [agave install](https://github.com/anza-xyz/agave/blob/master/install/agave-install-init.sh) file and export the PATH accordingly.

**Comment by buffalojoec** [comment]
@abhijayrajvansh is this a sporadic issue, or are you seeing it consistently? I'm running Apple silicon, and I don't have GNU `tar` installed.

```
$ which tar
/usr/bin/tar

$ which gnu-tar
gnu-tar not found

$ brew list gnu-tar
Error: No such keg: /opt/homebrew/Cellar/gnu-tar
```

I remember seeing this error sporadically when we first released 2.0, but it's been a while since I've spotted it again.

**Comment by abhijayrajvansh** [comment]
@buffalojoec so far many have encountered this issue, see [Solana StackExchange](https://solana.stackexchange.com/questions/4499/blockstore-error-when-starting-solana-test-validator-on-macos-13-0-1) and i believe it is a consistent problem with a default install of macOS.

i installed solana cli just few days back, and encountered this error. i'm running apple m2 macOS: Sonoma 14.6.1

```bash
❯ solana --version
solana-cli 1.18.23 (src:e5d267d9; feat:4215500110, client:Agave)
```

before raising this issue, i tested again with my intel-based macbook, macOS: Sonoma 14.6.1 and got the same error again. 

however in your case it seems that either you've installed gnu-tar without using homebrew that's why it can't list so instead of `which gnu-tar`, try `which gtar` in my system it's an alias and was linked to gtar:

```bash
❯ which gtar
/opt/homebrew/bin/gtar

❯ which tar
/opt/homebrew/opt/gnu-tar/libexec/gnubin/tar
```
or maybe it's linked with your default `tar`, in my system it was linked to default `bsdtar` (which comes pre-installed).

```bash
❯ la -l /usr/bin | grep tar
lrwxr-xr-x   1 root   wheel   6  4 Aug 16:01 tar -> bsdtar # required: gtar or gnu-tar
```
`solana-test-validator` or `anchor test` fails, as `hardened_unpack()` expects GNU tar, and if you dont have it installed i'm not sure how it's working but for me and many others it fails.

#### regarding the solution

i've read your comment on the linked pr #2840, that was a good solid point, will continue it there.

**Comment by joncinque** [comment]
As another option, we can stop shelling out to `tar` in the blockstore at https://github.com/anza-xyz/agave/blob/66c126b41ec2b55b3f747a4ac4e3ee6b439164a5/ledger/src/blockstore.rs#L4834-L4838

Instead, we can use the `tar` Rust crate to create the tarball: https://docs.rs/tar/latest/tar/ and then `bzip2` to compress it: https://docs.rs/bzip2/latest/bzip2/, and that way, it'll work on all platforms, including Windows.

Note that this change would be more invasive, and thus need to be tested thoroughly, but I think it's best solution. This was done in the past with https://github.com/solana-labs/solana/pull/19043

**Comment by abhijayrajvansh** [comment]
@joncinque agreed, that solves for every platform!

**Comment by zilayo** [comment]
facing the same issue on m2 sonoma 14.16.1

the fix mention above fixes it

```
brew install gnu-tar
export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
``` 

Using the rust tar crate instead sounds like a good idea.

**Comment by steviez** [comment]
> As another option, we can stop shelling out to `tar` in the blockstore at
> 
> https://github.com/anza-xyz/agave/blob/66c126b41ec2b55b3f747a4ac4e3ee6b439164a5/ledger/src/blockstore.rs#L4834-L4838
> 
> Instead, we can use the `tar` Rust crate to create the tarball: https://docs.rs/tar/latest/tar/ and then `bzip2` to compress it: https://docs.rs/bzip2/latest/bzip2/, and that way, it'll work on all platforms, including Windows.
> 
> Note that this change would be more invasive, and thus need to be tested thoroughly, but I think it's best solution. This was done in the past with [solana-labs#19043](https://github.com/solana-labs/solana/pull/19043)

Great suggestion @joncinque - seemingly multiple people have run into this, so I can take up making the change to avoid shelling out + testing
