### ISSUE TITLE
We are attempting to dump a block that we produced

### ISSUE THREAD

**Issue by JulI0-concerto** [anza-xyz/agave#2841]
#### Problem
My validator have panic with the following message:

```
We are attempting to dump a block that we produced. This indicates that we are producing duplicate blocks, or that there is a bug in our runtime/repla
y code which causes us to compute different bank hashes than the rest of the cluster. We froze slot 287809246 with hash Some(B4CX7tKBdzthkjFPyGS3oThLheoYg
7rm1k7dgk3T5NJu) while the cluster hash is EM9VrzvRmsCZCzFuXetTE899tXFRTsEXBd1HRoK69dq9" location="core/src/replay_stage.rs:1429:25" version="1.18.22 (src
:d47d8c83; feat:4215500110, client:JitoLabs)
```
I want to clarify that everything was running smoothly before it crashed.

**Comment by steviez** [comment]
There should have been a file created in:
```
YOUR_LEDGER_DIR/bank_hash_details/
```
It will have the slot and hash in the name, can you please share it ?

**Comment by JulI0-concerto** [comment]
@steviez 
https://drive.google.com/file/d/1bHJEmVaRQWrecwR1mNzC5Atz5cUG-Wwq/view?usp=sharing

**Comment by JulI0-concerto** [comment]
I am closing this issue. The root cause is primarily related to my build pipeline, which built on the master branch instead of tag 1.18.22.

**Comment by steviez** [comment]
> The root cause is primarily related to my build pipeline, which built on the master branch instead of tag 1.18.22.

Out of curiosity, how did you determine that building off master was the source of your node diverging ?

**Comment by JulI0-concerto** [comment]
I’m making this assumption because my node was reporting version 2.0.0. Is version 2.0.0 currently expected to function on the mainnet without the need for feature flag activations?

**Comment by steviez** [comment]
> Is version 2.0.0 currently expected to function on the mainnet without the need for feature flag activations?

Yes, we (Anza) aim to keep the next version consistent with the previous one. It is not guaranteed (we do make mistakes from time to time) and not recommended (we want to properly test / have chance for audit / etc), but as far as I know, the tip of v2.0 branch is currently compatible with mnb (as is the tip of master branch)

**Comment by JulI0-concerto** [comment]
I got this panic error again:
thread 'solReplayStage' panicked at core/src/replay_stage.rs:1429:25:
We are attempting to dump a block that we produced. This indicates that we are producing duplicate blocks, or that there is a bug in our runtime/replay co
de which causes us to compute different bank hashes than the rest of the cluster. We froze slot 290956095 with hash Some(Evmyd4mTSUpzQM1F1w7JWg3h7P7qqun8i
gr8EFP1Cbb7) while the cluster hash is 93J44XcJJtHBHMizgqwCQR2JDfEfP6WCPJonNrBEstk4
stack backtrace:

**Comment by JulI0-concerto** [comment]
Now I am sure I am with the right version 1.18.22-jito (paladin fork)
I already raised the issue to paladin team.

**Comment by OliverNChalk** [comment]
This has been resolved, it was an issue with the paladin patch. This can be closed

**Comment by steviez** [comment]
Oops, this one kind of fell off my radar but glad y'all figured it out.

In the future, please include details such as "paladin fork" in the initial report. Again, I didn't spend too much time on this but had I known that at first, my first question would have been "can you reproduce with vanilla Agave"
