### ISSUE TITLE
Considering upgrade outdated crate curve25519-dalek 3.2.1 -> 4.x

### ISSUE THREAD

**Issue by oneforalone** [anza-xyz/agave#290]
#### Problem

Since `curve25519-dalek 3.2.1` constrains its dependence `zeroize` to version `>=1, < 1.4`, this would conflict while using crate `tiny-bip39 1.0.0` and `solana-sdk` together.

#### Proposed Solution

I've tried to change `curve25519-dalek` version to the latest one `4.1.2`, and import it with path specification, it works properly with address generation. However, i saw there's some crates outdated, too. Are there some known problems that can not upgrade the dependencies? If not, please considering upgrade the dependencies version to the latest one, especially `curve2559-dalek`.

**Comment by oneforalone** [comment]
After checking with the dependecies tree via `cargo tree -d`, seems there's huge work to do for upgrade curve25519-dalek or zeroize.

Therefore, the current solution is to downgrade crate zeroize to v1.3.0 for other's who want to integrate solana-sdk to their project. Hopefully, others would get involved into this issue and make a full upgrade.

**Comment by oneforalone** [comment]
Finally, figuring out to how to integrate solana-sdk with latest zeroize crate. Just set the features to full, and everything went well. 

The full dependency config is:
```toml
solana-sdk = { version = "1.8.7", features = ["full"] }
```
Hope this helps.

**Comment by zilayo** [comment]
This still needs to be looked at imo. As well as `curve25519-dalek 3.2.1` there's also conflicts due to `aes-gcm-siv` and the programs repos.

```
error: failed to select a version for `zeroize`.
    ... required by package `aes-gcm-siv v0.10.3`
    ... which satisfies dependency `aes-gcm-siv = "^0.10.3"` of package `solana-zk-token-sdk v1.17.17`
    ... which satisfies dependency `solana-zk-token-sdk = ">=1.17.17, <=2"` of package `spl-token-2022 v2.0.1`
    ... which satisfies dependency `spl-token-2022 = "=2.0.1"` of package `solana-account-decoder v2.0.0 (https://github.com/anza-xyz/agave)`
    ... which satisfies git dependency `solana-account-decoder` of package `zil v0.1.0 (zil)`
versions that meet the requirements `>=1, <1.4` are: 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0

all possible versions conflict with previously selected packages.

  previously selected package `zeroize v1.5.3`
    ... which satisfies dependency `zeroize = "^1"` of package `ed25519-dalek v1.0.1`
    ... which satisfies dependency `ed25519-dalek = "=1.0.1"` of package `solana-sdk v2.0.0 (https://github.com/anza-xyz/agave)`
    ... which satisfies git dependency `solana-sdk` of package `zil v0.1.0 (zil)`
```
