### ISSUE TITLE
Solana block retention period

### ISSUE THREAD

**Issue by saravadeanil** [anza-xyz/agave#2918]
#### Problem

It seems that the block (slot) retention period on a Solana node is approximately 1.5 days. 

Is there any configuration or parameter to extend this retention period to around a week?

**Comment by cavemanloverboy** [comment]
I believe this is controlled by `--limit-ledger-size`

**Comment by saravadeanil** [comment]
Thanks @cavemanloverboy I will check it 👍

**Comment by joncinque** [comment]
[@cavemanloverboy's answer](https://github.com/anza-xyz/agave/issues/2918#issuecomment-2349107217) is correct, closing the issue
