### ISSUE TITLE
solana-test-validator in windows error

### ISSUE THREAD

**Issue by cuongnguyengit** [anza-xyz/agave#292]
Hi team,

I am new for solana. I have a trouble after setup finally above:

thread 'main' panicked at validator\src\bin\solana-test-validator.rs:118:86:
called Result::unwrap() on an Err value: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

Thanks for support.

**Comment by Nagaprasadvr** [comment]
Try running with administrator privileges

Also look for #24  if u run into other errors

**Comment by steviez** [comment]
As the previous poster pointed out, I think the problem you ran into was a permissions issue, and not actually something wrong with `solana-test-validator`. I'm going to close this issue out in favor of 24, as there are/were some other legitimate issues with Windows discussed in that one
