### ISSUE TITLE
geyser: add more slot statuses like FirstShredReceived, CreatedBank

### ISSUE THREAD

**Issue by fanatid** [anza-xyz/agave#2957]
#### Problem

It's not possible to implement a fully compatible Solana/Agave WebSocket (PubSub) replacement based on geyser. We only have access to processed / confirmed / finalized but with WebSocket additionally we have access to FirstShredReceived / Completed CreatedBank / Dead (https://github.com/anza-xyz/agave/blob/v2.0.10/rpc-client-api/src/response.rs#L187-L221). For example in https://github.com/Block-Logic/ping-thing-client we rely on FirstShredReceived to benchmark transaction landing and we would like to switch to geyser based tools.

#### Proposed Solution

Add more statuses to geyser.

cc @lijunwangs

**Comment by lijunwangs** [comment]
These seems to be some "new" slot status sate. We should be able to support it in Geyser -- will come up with a PR soon.

**Comment by fanatid** [comment]
A related issue in the original repo https://github.com/solana-labs/solana/issues/32958

**Comment by fanatid** [comment]
@lijunwangs looks like all existing statuses implemented? :rocket:

**Comment by lijunwangs** [comment]
Right. I would recommend verifying against our latest master build. @fanatid
