### ISSUE TITLE
Flaky Test: solana-cargo-build-sbf::crates test_target_and_out_dir

### ISSUE THREAD

**Issue by anza-team** [anza-xyz/agave#3004]
_AUTO-GENERATED. DO NOT EDIT._

[📝 Buildkite Analytics](https://buildkite.com/organizations/anza/analytics/suites/agave/tests/5bfdb993-1d4d-83f5-92c3-87f37c2c0946)

**Comment by yihau** [comment]
it's a ci agent issue. it's no related to the test itself
