### ISSUE TITLE
Liberate the solana-client family from solana-sdk

### ISSUE THREAD

**Issue by kevinheavey** [anza-xyz/agave#3027]
#### Problem
solana-client and its constituent crates (listed further below) can compile much faster if we remove solana-sdk and solana-program dependencies, by ripping out what is needed from those crates.

#### Proposed Solution
At the time of writing, here are the modules that still need to be made available outside solana-program / solana-sdk.

- solana_program::epoch_schedule #3021
- solana_program::feature #3120
- solana_program::fee_calculator #2969
- solana_program::message #3704 
- solana_program::nonce #3082
- solana_program::rent #3022 
- solana_program::slot_hashes #3010 
- solana_program::sysvar #3680 
- solana_sdk::account #2294 
- solana_sdk::account_utils #3174  
- solana_sdk::client #3829 
- solana_sdk::commitment_config #2136 
- solana_sdk::epoch_info #3028
- solana_sdk::genesis_config::ClusterType #3372
- solana_sdk::inflation #2970 
- solana_sdk::packet #3029 
- solana_sdk::quic #3119 
- solana_sdk::reward_type #2971 
- solana_sdk::signer #3087 
- solana_sdk::timing #3327 
- solana_sdk::transaction #3634 
- solana_sdk::transaction_context #3132 
- solana_sdk::transport #2295

Here are those modules grouped by each crate that depends on them:

**solana-account-decoder-client-types** (will be created by #2872)
- solana_sdk::account

**solana-transaction-status-client-types** (#3831)
- solana_sdk::commitment_config
- solana_program::message
- solana_sdk::reward_type
- solana_sdk::transaction
- solana_sdk::transaction_context

**solana-feature-set** (#3140):
- solana_program::epoch_schedule

**solana-vote-program** (required by solana-rpc-client, just needs #3462)

**solana-rpc-client-api** (#3682):
- solana_program::fee_calculator
- solana_sdk::account
- solana_sdk::commitment_config
- solana_sdk::inflation
- solana_sdk::transaction
- solana_sdk::transport

**solana-rpc-client** (#3833)
- solana_program::epoch_schedule
- solana_program::vote
- solana_sdk::feature
- solana_program::message
- solana_program::sysvar
- solana_sdk::account
- solana_sdk::commitment_config
- solana_sdk::epoch_info
- solana_sdk::transaction

**solana-rpc-client-nonce-utils** (#3440):
- solana_program::nonce
- solana_sdk::account
- solana_sdk::account_utils
- solana_sdk::commitment_config

**solana-metrics** (#3374):
- solana_sdk::genesis_config::ClusterType
- solana_sdk::timing

**solana-perf** (#3457):
- solana_program::message
- solana_sdk::packet
- solana_sdk::timing

**solana-perf** (#3718)

**solana-transaction-metrics-tracker** (#3439):
- solana_sdk::packet
- solana_perf

**solana-streamer** (#3445):
- solana_perf
- solana_sdk::packet
- solana_sdk::quic
- solana_sdk::timing
- solana_sdk::transport

**solana-connection-cache** (#3436) :
- solana_sdk::signer
- solana_sdk::timing
- solana_sdk::transport

**solana-quic-client** (#3441):
- solana_sdk::quic
- solana_sdk::signer
- solana_sdk::transport

**solana-thin-client** (#3841):
- solana_program::message
- solana_sdk::account
- solana_sdk::client
- solana_sdk::commitment_config
- solana_sdk::signer
- solana_sdk::transaction
- solana_sdk::transport

**solana-tpu-client** (#3842):
- solana_program::message
- solana_sdk::client
- solana_sdk::commitment_config
- solana_sdk::signer
- solana_sdk::transaction
- solana_sdk::transport

**solana-udp-client** (#3437):
- solana_sdk::packet
- solana_sdk::signer
- solana_sdk::transport

**solana-client** (#3844):
- solana_sdk::client
- solana_sdk::commitment_config
- solana_sdk::epoch_info
- solana_sdk::quic
- solana_sdk::signer
- solana_sdk::timing
- solana_sdk::transaction
- solana_sdk::transport

**solana-clap-utils** (#3626):
- solana_sdk::signer
- solana_sdk::genesis_config::ClusterType

**solana-net-utils** (#3843)

**Comment by kevinheavey** [comment]
Finished off by #3844!

**Comment by joncinque** [comment]
Really great work, thanks for all your efforts!
