### ISSUE TITLE
SVM entry point requires builtins registered in two different places

### ISSUE THREAD

**Issue by LucasSte** [anza-xyz/agave#303]
#### Problem

In order to use the SVM, we must register the builtins as it is now done in the `add_builtin` function in `bank.rs` ([link](https://github.com/anza-xyz/agave/blob/64412096829241e5c70d537403584dbc9e04ee93/runtime/src/bank.rs#L7089-L7098)), and then pass them to `load_and_execute_sanitized_transactions` as a vector of public keys.

#### Proposed Solution

Ideally, we would only register the builtins on the SVM once, obviating the vector of public keys passed to `load_and_execute_sanitized_transactions`.

**Comment by pgarg66** [comment]
It might make sense to move `builtin_programs: HashSet<Pubkey>,` and `add_builtin()/remove_builtin()` to `TransactionBatchProcessor`. That'll move the bookkeeping to SVM, and the need for passing it via `load_and_execute_sanitized_transactions` will go away.
