### ISSUE TITLE
Flaky Test: solana-cargo-build-sbf::crates test_sbfv2

### ISSUE THREAD

**Issue by anza-team** [anza-xyz/agave#3075]
_AUTO-GENERATED. DO NOT EDIT._

[📝 Buildkite Analytics](https://buildkite.com/organizations/anza/analytics/suites/agave/tests/e036c3ea-6624-8505-82dc-1f2f5b36ce44)

**Comment by yihau** [comment]
it's a ci agent issue. it's no related to the test itself
