### ISSUE TITLE
Flaky Test: solana-cargo-build-sbf::crates test_out_dir

### ISSUE THREAD

**Issue by anza-team** [anza-xyz/agave#3076]
_AUTO-GENERATED. DO NOT EDIT._

[📝 Buildkite Analytics](https://buildkite.com/organizations/anza/analytics/suites/agave/tests/9f3e6b01-3d0d-8e64-87b0-f07a0801002a)

**Comment by yihau** [comment]
it's a ci agent issue. it's no related to the test itself
