### ISSUE TITLE
Flaky Test: solana-cargo-build-sbf::crates test_generate_child_script_on_failure

### ISSUE THREAD

**Issue by anza-team** [anza-xyz/agave#3077]
_AUTO-GENERATED. DO NOT EDIT._

[📝 Buildkite Analytics](https://buildkite.com/organizations/anza/analytics/suites/agave/tests/e2be9972-a858-8901-9bc4-04483797cd10)

**Comment by yihau** [comment]
it's a ci agent issue. it's no related to the test itself
