### ISSUE TITLE
ledger-tool: The snapshot is being created in a different folder than expected

### ISSUE THREAD

**Issue by diman-io** [anza-xyz/agave#3117]
#### Problem
If the positional argument `output_directory` is omitted, the snapshot will be created in the `--ledger` directory. However, according to https://github.com/anza-xyz/agave/blob/4cc7b90484ab8054090b78ea59645b5904e57efb/ledger-tool/src/main.rs#L1723-L1745 it was expected to be placed in the `--incremental-snapshot-archive-path` directory.

And I recall the same behavior during the previous restart - a full snapshot was created, and it was also placed in the ledger folder.

Everything was fine before (maybe about a year ago).

**Comment by steviez** [comment]
Can you please share the full set of arguments you passed to `ledger-tool` ? Can you also confirm which version you were running with; I assume this was encountered for the [planned testnet restart](https://github.com/anza-xyz/agave/wiki/2024-10-09-Testnet-Rollback-and-Restart) and that you were running v2.0.x

**Comment by diman-io** [comment]
Sure
```
agave-ledger-tool -l /mnt/disk2/ledger create-snapshot --incremental --snapshot-archive-path /mnt/disk3/validator/snapshots/ --incremental-snapshot-archive-path /mnt/disk3/validator/incremental_snapshots/ --hard-fork 296876255 --deactivate-feature-gate 9bn2vTJUsUcnpiZWbu2woSKtTGW3ErZC9ERv88SDqQjK ed9tNscbWLYBooxWA7FE2B5KHWs8A6sxfY8EzezEcoo EenyoWx9UMXYKpR8mW5Jmfmy2fRjzUtM7NduYMY8bx33 --remove-account SysvarEpochRewards1111111111111111111111111 --enable-capitalization-change --accounts /mnt/disk3/validator/accounts --accounts-index-path /mnt/disk3/validator/accounts_index/ --accounts-hash-cache-path /mnt/disk3/validator/accounts_hash_cache/ -- 296876255
```

**Comment by diman-io** [comment]
yes, it was `2.0.13`

**Comment by steviez** [comment]
Thanks @diman-io, there is indeed a bug that I introduced 😬 . The issue was first introduced in `v2.0` branch, so I'll likely try to backport the patch there
