### ISSUE TITLE
Cargo test failed

### ISSUE THREAD

**Issue by web3dopamine** [anza-xyz/agave#3149]
#### Problem
one of the test failed while running ./cargo test

![image](https://github.com/user-attachments/assets/cd0b9fb2-c293-44bb-9a13-296b8cbfcae1)

**Comment by steviez** [comment]
This is an issue on your side:
```
called `Result::Unwrap() on an `Err` value: UnableToSetOpenFileDescriptorLimit
```

**Comment by web3dopamine** [comment]
![image](https://github.com/user-attachments/assets/020f9e10-cc1d-4f05-a9aa-baecd4bb1ba2)

so i didnt add this thats why?

**Comment by OliverNChalk** [comment]
I would argue this is a failing of the repository not the user. It's pretty standard to be able to:

```
git clone
cargo test
```

Which is not true for this codebase
