### ISSUE TITLE
Too many sandwich attacks

### ISSUE THREAD

**Issue by cielu** [anza-xyz/agave#3230]
Hey man, the Solana chain is full of sandwich attacks now. 

Can you deal with it?

 I made three transactions today and was attacked by the other party for 2000u. Yesterday, I was also attacked for 1500u. 

And this problem started yesterday.

I don’t know why there are so many sandwich attacks suddenly.

**Comment by liqtags** [comment]
Use JittoBundle yourself, it's cheap on tips.

**Comment by cielu** [comment]
> Use JittoBundle yourself, it's cheap on tips.

OK， Thank u
