### ISSUE TITLE
Bug: TooManyAccountLocks Check Incorrect

### ISSUE THREAD

**Issue by jwalin12** [anza-xyz/agave#3395]
#### Problem

The [current](https://github.com/anza-xyz/agave/blob/ccbe01dd332ab6b75cd2091fb359e4ad8fea0c2c/accounts-db/src/account_locks.rs#L123) TooManyAccountLocks check looks at the [length](https://github.com/anza-xyz/agave/blob/ccbe01dd332ab6b75cd2091fb359e4ad8fea0c2c/sdk/program/src/message/account_keys.rs#L70) of AccountKeys. The length check only checks the amount of accounts loaded, not the number of writable (locked) accounts. This prevents developers from utilizing versioned transactions effectively, as even if the number of writable accounts in the transaction is less than the limit the transaction does not go through. This is blocking for a few features on our app right now.

#### Proposed Solution

Update the TooManyAccountLocks check to read writable accounts.

**Comment by khuddite** [comment]
I am taking a look at this issue, thanks for the details @jwalin12

**Comment by apfitzge** [comment]
This is not a bug and is the intended behavior. Read locks are still locks.
Changing it to only count writable account keys would lead to inconsistency in consensus w/o feature-gating.

There is already a feature for increasing the account limit from 64 to 128:

```rust
pub mod increase_tx_account_lock_limit {
    solana_pubkey::declare_id!("9LZdXeKGeBV6hRLdxS1rHbHoEUsKqesCC2ZAPTPKJAbK");
}
```
