### ISSUE TITLE
'$' sign at the beginning of bash commands prevent copy/paste

### ISSUE THREAD

**Issue by Phantom-2** [anza-xyz/agave#3401]
#### Problem

'$' at the beginning of bash commands in [ README.md](https://github.com/anza-xyz/agave/blob/master/README.md) prevent copy/paste.

#### Proposed Solution
Delete "$" at the beginning of bash commands in [ README.md](https://github.com/anza-xyz/agave/blob/master/README.md) file.

**Comment by steviez** [comment]
I personally prefer the `$`'s; they reinforce when a new command starts.

> prevent copy/paste.

You can still just select the the text and exclude the `$` from your selection before you copy
