### ISSUE TITLE
Feature Gate: extends Turbine fanout experiment to wider fanout values

### ISSUE THREAD

**Issue by behzadnouri** [anza-xyz/agave#3432]
### SIMD

-

### Description

https://github.com/anza-xyz/agave/pull/2373

Based on previous Turbine fanout experiment, larger fanouts are more effective in propagating shreds and reducing repairs: https://discord.com/channels/428295358100013066/478692221441409024/1265782094211321897

However the optimal fanout value cannot be inferred from the experiment.

In order to identify optimal fanout value, this commit extends the experiment with wider fanout values.

### Feature ID

BZn14Liea52wtBwrXUxTv6vojuTTmfc7XGEDTXrvMD7b

### Activation Method

Single Core Contributor

### Deployment Considerations

-

### Minimum Beta Version

v2.0.10

### Minimum Stable Version

v1.18.24

**Comment by willhickey** [comment]
Replacing this with:
https://github.com/orgs/anza-xyz/projects/9/views/1?pane=issue&itemId=86808518&issue=anza-xyz%7Cfeature-gate-tracker%7C63

Creating the feature gates in the anza-xyz/feature-gate-tracker makes labels accessible and keeps permissions consistent
