### ISSUE TITLE
Feature Gate: enforce retransmitter signature verification

### ISSUE THREAD

**Issue by behzadnouri** [anza-xyz/agave#3433]
### SIMD

-

### Description

https://github.com/anza-xyz/agave/pull/1840

Need to verify if the shred is retransmitted by the expected parent node in Turbine tree.

### Feature ID

BZ5g4hRbu5hLQQBdPyo2z9icGyJ8Khiyj3QS6dhWijTb

### Activation Method

Single Core Contributor

### Deployment Considerations

-

### Minimum Beta Version

v2.0.6

### Minimum Stable Version

v2.0.6

**Comment by willhickey** [comment]
Replacing with:
https://github.com/orgs/anza-xyz/projects/9/views/1?pane=issue&itemId=86809013&issue=anza-xyz%7Cfeature-gate-tracker%7C64
