### ISSUE TITLE
Fresh install of 2.0.15 seems to loop forever

### ISSUE THREAD

**Issue by bartenbach** [anza-xyz/agave#3558]
#### Problem
I experienced a strange problem when installing 2.0.15 from scratch on a brand new server. The validator was stuck in an endless loop - but never really errored out or panicked.

This same behavior was described by several others on Discord.

This was the first report that I found: https://discord.com/channels/428295358100013066/560174212967432193/1304527333352407222

I later experienced the same confusing loop
```
[2024-11-09T03:47:07.285447759Z INFO  solana_accounts_db::read_only_accounts_cache] AccountsReadCacheEvictor has stopped
[2024-11-09T03:47:07.285433379Z INFO  solana_accounts_db::accounts_db] Background account hasher is stopping because: receiving on an empty and disconnected channel
[2024-11-09T03:47:07.285553879Z INFO  solana_accounts_db::accounts_db] Background account hasher has stopped
[2024-11-09T03:47:19.670320358Z WARN  solana_perf] CUDA is disabled
[2024-11-09T03:47:19.670372128Z INFO  solana_perf] AVX detected
[2024-11-09T03:47:19.670376008Z INFO  solana_perf] AVX2 detected
```

#### Proposed Solution
It seems if you downgrade to 1.18.26, fetch a snapshot, and catch up, THEN you can easily upgrade to 2.0.15 and restart.

I don't know why, but that worked for others and worked for me.

**Comment by brooksprumo** [comment]
I'm trying to reproduce this. I built v2.0.15 and started up a node from scratch. It downloaded snapshots and was able to load successfully. The node is currently catching up.

(Edit: Node has caught up successfully)

Can you share more information about the machine? OS/kernel, and if you built the binaries from source or downloaded them? If you have the full log from the run, can you upload it here too?

**Comment by bartenbach** [comment]
> I'm trying to reproduce this. I built v2.0.15 and started up a node from scratch. It downloaded snapshots and was able to load successfully. The node is currently catching up.
> 
> (Edit: Node has caught up successfully)
> 
> Can you share more information about the machine? OS/kernel, and if you built the binaries from source or downloaded them? If you have the full log from the run, can you upload it here too?

Strange. I'm not sure what happened.

Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-47-lowlatency x86_64)
Built from source

Log is too big. "25 MB are allowed, 55 MB were attempted to upload." I do have the log file though. Suggestions?

**Comment by brooksprumo** [comment]
> Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-47-lowlatency x86_64) Built from source

Gotcha, noted. 

---

> Log is too big. "25 MB are allowed, 55 MB were attempted to upload." I do have the log file though. Suggestions?

Can you try to compress it and see if that's sufficient? Otherwise, maybe dropbox/etc?

---

Can you also check the number of account storage files? Something like
```bash
$ ls -l ledger/accounts/run | wc -l
```
should work.

**Comment by bartenbach** [comment]
Compressed log: [fucked.log.gz](https://github.com/user-attachments/files/17695569/fucked.log.gz)

Number of account storage files is 418991 - but that _might_ not be helpful since the node has since been fixed and is running fine now.

**Comment by brooksprumo** [comment]
> Compressed log

Thanks. A few things I notice:
* It looks like this is from multiple runs. That's fine, just noting.
* It looks like there are missing logs. Are you by chance running with `RUST_LOG=solana=info` by chance? If yes, then all of the agave logs will be stripped out. I'd recommend either removing the RUST_LOG export entirely, or using `RUST_LOG=agave=info,solana=info`.

It's hard to diagnose what might be happening without seeing a panic message or knowing if there's any errors in the syslog.

**Comment by bartenbach** [comment]
> > Compressed log
> 
> Thanks. A few things I notice:
> 
> * It looks like this is from multiple runs. That's fine, just noting.
> * It looks like there are missing logs. Are you by chance running with `RUST_LOG=solana=info` by chance? If yes, then all of the agave logs will be stripped out. I'd recommend either removing the RUST_LOG export entirely, or using `RUST_LOG=agave=info,solana=info`.
> 
> It's hard to diagnose what might be happening without seeing a panic message or knowing if there's any errors in the syslog.

Thanks for this. I had no idea I was missing logs. That makes a lot of sense!

I'll update my RUST_LOG with your suggestion. I think I'll close this because of the lack of information and lack of others experiencing the same thing and write it off as a fluke.
