### ISSUE TITLE
Can never keep up with the mainnet data

### ISSUE THREAD

**Issue by songqingshududu** [anza-xyz/agave#3564]
![image](https://github.com/user-attachments/assets/e4e7d02e-1e5f-4995-b009-3a2b1afd5561)
My solana version is 1.18.26, and the cluster version of mainnet synchronization data is 2.0.15. Do I need to upgrade to version 2.0.15 as well

**Comment by songqingshududu** [comment]
![image](https://github.com/user-attachments/assets/f641d2a7-62d7-40f2-8bfd-fee9255e4fe4)
This is the server configuration

**Comment by songqingshududu** [comment]
exec solana-validator \
    --identity /home/ubuntu/sol/validator-keypair.json \
    --accounts /home/ubuntu/sol/accounts-dir \
    --log /home/ubuntu/sol/solana-validator.log \
    --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
    --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --ledger ledger \
    --only-known-rpc \
    --full-rpc-api \
    --enable-rpc-transaction-history \
    --no-voting \
    --rpc-port 8899 \
    --rpc-bind-address 127.0.0.1 \
    --rpc-threads 10000 \
    --private-rpc \
    --dynamic-port-range 8000-8020 \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
    --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
    --wal-recovery-mode skip_any_corrupted_record \
    --limit-ledger-size 1073741824000 \
    --minimal-snapshot-download-speed 6442450944 \
    --account-index program-id spl-token-owner  spl-token-mint

**Comment by steviez** [comment]
Hi @songqingshududu - We don't offer "validator/rpc support" here on GitHub. Rather, you can try joining us Discord in:
https://discord.com/invite/solana

After reading the guidelines and self-assigning roles, your question might be suited for validator-beginners as there is not nearly enough information provided from you to know if this is an RPC-specific issue you're hitting.

That being said, this value is almost assuredly too large, and I would imagine your node is running out of disk space:
```
--limit-ledger-size 1073741824000
```

**Comment by Peterwang366** [comment]
请问后续你有解决吗？
