### ISSUE TITLE
Testnet Manual Review of Partitioned Epoch Rewards

### ISSUE THREAD

**Issue by steviez** [anza-xyz/agave#3619]
### Problem
With the activation of Partitioned Epoch Reward (PER) on testnet (feature key `PERzQrt5gBD1XEe2c9XdFWqwgHY3mr7cYWbm5V772V8`), we wanted to do a sanity check to ensure that everything is working as expected.

### Setup
The testing is being performed with the `v2.0.15` tag:
```
$ agave-validator --version
agave-validator 2.0.15 (src:f8f3fe31; feat:607245837, client:Agave)
$ agave-ledger-tool --version
agave-ledger-tool 2.0.15 (src:f8f3fe31; feat:607245837, client:Agave)
```
The node was running against testnet for several days. The node was then stopped shortly after epoch 710 started, and a snapshot was created at the final slot of epoch 709 (`301,196,255`) to facilitate testing:
```
$ agave-ledger-tool create-snapshot 301196255 --ledger ~/ledger &> 301196255_create_snap.log
```
As an extra precaution, the bank hash computed for `301196255` from ledger-tool was compared to what was computed by the validator and confirmed to match:
```
$ grep "bank frozen: 301196255" logs/solana-validator.log
[... INFO  solana_runtime::bank] bank frozen: 301196255 hash: 6myinmvw7JcGEMHNgzMh3kzb1iP7AnpDmymdoVP4Bt8N ...

$ grep "bank frozen: 301196255" ledger/301196255_create_snap.log 
[... INFO  solana_runtime::bank] bank frozen: 301196255 hash: 6myinmvw7JcGEMHNgzMh3kzb1iP7AnpDmymdoVP4Bt8N ...
```

### PER distribution completion slot
We need to determine when the reward distributions will be complete in order to test it. We can start with a `getBlock` query that tells us how many partitions (blocks) it will take to distribute, noting that `301196256` is the first block in epoch 710:
<details>
<summary>getBlock query</summary>

```
curl https://api.testnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0","id":1,
    "method":"getBlock",
    "params": [
      301196256,
      {
        "encoding": "json",
        "maxSupportedTransactionVersion":0,
        "transactionDetails":"none",
        "rewards":false
      }
    ]
  }
'
```
</details>

<details>
<summary>getBlock response</summary>

```
{
  "jsonrpc": "2.0",
  "result": {
    "blockHeight": 261346927,
    "blockTime": 1731355931,
    "blockhash": "5PZeJdHFiUuAo3Fs65L3GDASyyE866nttkRxMhuRwjvy",
    "numRewardPartitions": 129,
    "parentSlot": 301196255,
    "previousBlockhash": "5VZB6NhRzNnBpCq4uraghtddm2BUVDERVaEMnhctgaHq"
  },
  "id": 1
}
```
</details>

With the response, we see `numRewardPartitions: 129`. Now, a `getBlocksWithLimit` query will tell us when the distribution will be done. We add 1 since the first block will distributes the vote account rewards, and the 129 next blocks distribute the stake account rewards for a total of 130 blocks:
<details>
<summary>getBlocksWithLimit query</summary>

```
curl https://api.testnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id":1,
    "method":"getBlocksWithLimit",
    "params":[301196256, 130]
  }
'
```
</details>

<details>
<summary>getBlocksWithLimit response</summary>

```
{
  "jsonrpc": "2.0",
  "result": [
    301196256,
    ...
    301196396
  ],
  "id": 1
}
```
</details>

This means that `301196396` is the final slot that will include PER reward distribution, and its' child (`301196397`) will be the first slot after reward distribution has completed. As a final precaution, we can use `ledger-tool` to extract `SysvarEpochRewards1111111111111111111111111` and ensure that state matches what we expect at each of those slots:
<details>
<summary>ledger-tool runs</summary>

```
$ agave-ledger-tool accounts --ledger ~/ledger --account SysvarEpochRewards1111111111111111111111111 --halt-at-slot 301196395 --include-sysvars --encoding jsonParsed

SysvarEpochRewards1111111111111111111111111:
  balance: 0.00145464 SOL
  owner: 'Sysvar1111111111111111111111111111111111111'
  executable: false
  slot: 301196395
  rent_epoch: 18446744073709551615
  data_len: 81
  data: '{"program":"sysvar","parsed":{"info":{"active":true, ...},"type":"epochRewards"},"space":81}'
  encoding: "jsonParsed"

$ agave-ledger-tool accounts --ledger ~/ledger --account SysvarEpochRewards1111111111111111111111111 --halt-at-slot 301196396 --include-sysvars --encoding jsonParsed

SysvarEpochRewards1111111111111111111111111:
  balance: 0.00145464 SOL
  owner: 'Sysvar1111111111111111111111111111111111111'
  executable: false
  slot: 301196396
  rent_epoch: 18446744073709551615
  data_len: 81
  data: '{"program":"sysvar","parsed":{"info":{"active":false, ...},"type":"epochRewards"},"space":81}'
  encoding: "jsonParsed"
```
</details>

As the ledger-tool output shows, the `active` field of the sysvar toggles from true to false between slot `301196395` and `301196396`. We also note that the boolean is toggled to `false` in the last slot of distribution. Thus, we can feel confident that we have identified the final PER distribution slot. 

#### Restarting from snapshots within PER distribution window
The objective with this test is to ensure that a node can be restarted from snapshot within the rewards distribution window and compute consistent reward results as a node that ran continuously through. So, the test will advance the snapshot block by block and then verify. The specific commands involved 
- Start with a ledger with snapshot at slot `301196255` (the final slot of previous epoch)
- For each `BLOCK` from the `getBlocksWithLimit` response above:
    - Run `agave-ledger-tool create-snapshot BLOCK ...`
    - Run `agave-ledger-tool verify --halt-at-slot 301196500 ...`
    - Ensure that the bank hash computed by `verify` command matches what `agave-validator` originally produced
        - This is done by saving the `agave-ledger-tool` logs

The above mentioned procedure is carried out with this script: [per_create_and_verify_snaps_script.txt](https://github.com/user-attachments/files/17742947/per_create_and_verify_snaps_script.txt). And for completeness, the bank hash from `agave-validator` that I'm comparing against is:
```
[...INFO  solana_runtime::bank] bank frozen: 301196500 hash: 8WYoVEQb5hFL67CHudGxSRJe9mW8czHb6yqHxzx9R6QY ...
```
And, scanning the generated logs, I see that each run of `agave-ledger-tool verify` yielded this correct hash:
```
$ ls -l ledger/verify/ | grep "verify_from" | wc -l
129
$ grep "bank frozen: 301196500 hash: 8WYoVEQb5hFL67CHudGxSRJe9mW8czHb6yqHxzx9R6QY" ledger/verify/* | wc -l
129
```

#### Comparing Blockstore rewards from restart within PER distribution window
The objective of this test is to restart a node from a snapshot within the rewards distribution window and ensure that the rewards information that would be stored to the Blockstore (and eventually BigTable) matches what would be stored as if the node were running continuously through. The specific steps are:
- Start with a ledger with snapshot at slot `301196255` (the final slot of previous epoch)
- Generate the rewards information into the Blockstore (https://github.com/anza-xyz/agave/pull/3872)
- Now, generate a snapshot at slot `301196257` (the second slot of new epoch, first slot of stake reward distribution)(
- Run ledger-tool and compare the rewards returned from each frozen `Bank` against what was written to the `Blockstore` from earlier
    - Done with [bstore_comparison.patch](https://github.com/user-attachments/files/17987915/bstore_comparison.patch)

After running the above sequence and storing output into a log file, I see that everything does indeed match:
```
$ cat ~/ledger/per_blockstore_comparison.log | grep ERROR
[2024-12-03T05:27:03.891534348Z ERROR solana_ledger::blockstore_processor] PER test: match from previous run for slot 301196258: true
...
[2024-12-03T05:27:26.062022187Z ERROR solana_ledger::blockstore_processor] PER test: match from previous run for slot 301196396: true
$ cat ~/ledger-testnet/per_test.log | grep ERROR | wc -l
132
$ cat ~/ledger-testnet/per_test.log | grep ERROR | grep true | wc -l
132
$ cat ~/ledger-testnet/per_test.log | grep ERROR | grep false | wc -l
0
```
It should be noted that I had to sort the rewards by pubkey in order to get the test to match; prior to sorting, the vectors of rewards failed the built in equality check. This is known and expected behavior so no cause for alarm.

**Comment by steviez** [comment]
@jstarry @willhickey - FYI, the script I mentioned in final section is currently running. Given that it is creating 129 snapshots + doing 129 runs of verify, it will take a while. The script looks to be doing alright though so going to let it run overnight and check on it in the mornign

**Comment by jstarry** [comment]
Thanks @steviez, this looks more than sufficient to me. I know @CriesofCarrots wanted to look at rocksdb rewards to verify they were the same as well but I feel comfortable without setting up extra testing for that because that code path isn't really specific to snapshot testing. If there was an issue with the snapshot rewards it would show up in the accounts hash. @willhickey I think we're ready to move forward with devnet activation

**Comment by willhickey** [comment]
@steviez did the overnight run succeed for the 129 verifies?

**Comment by steviez** [comment]
> @steviez did the overnight run succeed for the 129 verifies?

Ahh yes, sorry; I DM'd Justin that but didn't post back here. But yes, I updated my description above in place. Namely, this piece:
> And, scanning the generated logs, I see that each run of agave-ledger-tool verify yielded this correct hash:
>
> $ ls -l ledger/verify/ | grep "verify_from" | wc -l
> 129
> $ grep "bank frozen: 301196500 hash: 8WYoVEQb5hFL67CHudGxSRJe9mW8czHb6yqHxzx9R6QY" ledger/verify/* | wc -l
> 129

**Comment by CriesofCarrots** [comment]
> I feel comfortable without setting up extra testing for that because that code path isn't really specific to snapshot testing. If there was an issue with the snapshot rewards it would show up in the accounts hash.

Fwiw, I don't really understand this comment, @jstarry . Maybe "snapshot" in the second sentence is a typo?
Snapshotting is the not the only thing that needed to be tested.

But if you are confident in it, 🔥 🔥

**Comment by jstarry** [comment]
Oh I thought that the main thing we were testing is making sure we keep consensus. Since there are special cases in snapshots, I thought we wanted to focus on that.

**Comment by steviez** [comment]
The feature was set for activation on devnet, so I think that means we feel confident in the additional manual testing we performed and we can close this issue out. We can always reopen if there is another aspect that we'd like to review
