### ISSUE TITLE
failed to reload a modified plugin when the .so file path retained the same 

### ISSUE THREAD

**Issue by z307287280** [anza-xyz/agave#3745]
#### Problem
Here is what I have done:
1) I loaded a plugin path "/home/1.so" (say name is "test1") and then unload it.
2) I changed the name() function's return to "test2" and then compile a new plugin retains the same plugin path "/home/1.so"
3) Load the new plugin and check the plugin list, the result is "test1" but not "test2"

I believe the first plugin is not be unloaded from the memory even the plugin manager has executed self._drop_plugin(idx).
The **libloading::Library::new** function actually using "**RTLD_LAZY | RTLD_LOCAL**" flag which may retrieve the original plugin back to the plugin vector.

**Comment by steveluscher** [comment]
Duplicate #3620.
