### ISSUE TITLE
Multisig mint with offline signing does not work using spl-token

### ISSUE THREAD

**Issue by stelgic** [anza-xyz/agave#3765]
I have created mint with `--mint-decimals 6` and when I try to mint some tokens i got error on finalize multisig

```
Minting 5 tokens
  Token: mntXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  Recipient: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Error: Client(PresignerError(VerificationFailure))
```

I am running the same command shown in the documentation and using different machines on different timezone.

[Offline Multisig](https://spl.solana.com/token#example-offline-signing-with-multisig)

**Comment by joncinque** [comment]
Hi there, the spl-token CLI is developed at https://github.com/solana-labs/solana-program-library -- can you add your issue there instead? Also, be sure to provide the full commands that you're running, which will help us debug more quickly.

If you're getting a presigner error, it means that your commands are not generating the same transaction, so be sure that no parameters are missing or different between your offline and online commands.
