### ISSUE TITLE
cargo build fetches wrong plaftorm-tools archive

### ISSUE THREAD

**Issue by AnarchSun** [anza-xyz/agave#3802]
#### Problem
myenvjustinlanouette@iMac-de-Justin sns-integration % cargo build-bpf --manifest-path=Cargo.toml --bpf-out-dir=../../target/deploy

[2024-11-26T20:28:52.350094000Z ERROR cargo_build_sbf] Failed to install platform-tools: HTTP status client error (404 Not Found) for url (https://github.com/anza-xyz/platform-tools/releases/download/v1.42/platform-tools-osx-x86_64.tar.bz2)
myenvju
 

#### Proposed Solution
add 1.42 ios intel compatible file or edit install.sh to fetch v1.41

**Comment by AnarchSun** [comment]
[package]
name = "sns-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.1.2"
solana-program = "2.1.2"

what version fetches v1.41?

**Comment by joncinque** [comment]
This repository does not contain the platform tools -- check out https://github.com/anza-xyz/platform-tools/issues/66 for a more appropriate issue
