### ISSUE TITLE
cargo build-sbf fails with Failed to install platform-tools: HTTP status client error (404 Not Found) error

### ISSUE THREAD

**Issue by farawaystar** [anza-xyz/agave#4028]
when running cargo build-sbf on Mac, I get this error
ERROR cargo_build_sbf] Failed to install platform-tools: HTTP status client error (404 Not Found) for url (https://github.com/anza-xyz/platform-tools/releases/download/v1.42/platform-tools-osx-x86_64.tar.bz2)

tried following solutions but didn't work:
-> reinstalling latest solana version from Anza: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
-> clearing cache using cargo clean
-> cargo update
-> rustup update
-> ensuring cargo.toml file has same solana version and my CLI
-> cargo build-bpf also gives the same error

help greatly appreciated

**Comment by joncinque** [comment]
Hi there, this is a duplicate of #3566 -- check out the resolution in the linked issue there
