### ISSUE TITLE
"Error Corrections and Improvements to Solana's Documentation"

### ISSUE THREAD

**Issue by Nataalabashir** [anza-xyz/agave#4127]
Dear Solana Team,

I'm Nata'ala Bashir Kurawa, and I'm excited to contribute to the Solana ecosystem. I've reviewed the Solana overview and identified some errors and corrections (attached below).

I believe my corrections can help improve the accuracy and clarity of Solana's documentation. I'm eager to collaborate with the Solana team to ensure the platform's continued success.

Thank you for considering my contributions. I look forward to the opportunity to work together.

Best regards,
Nata'ala Bashir Kurawa

Solana Address: H8AJW9VUv5jgZ5RGeJZMTohYiGzfsTzu5bvAnPaJCec7
Email: [nataalabashirkurawa@gmail.com](mailto:nataalabashirkurawa@gmail.com)
Phone Number: +2349072300190

Error Corrections:

1- Introduction: Solana is a decentralized, open-source blockchain platform. (Missing: mention of fast and scalable)
2- Consensus: Solana uses a novel consensus algorithm called Proof of History (PoH). _(Incomplete: missing explanation of PoH) and its use of verifiable delay functions (VDFs).

Block Time: 400 milliseconds (Incorrect: block time is 400-800 milliseconds)
3- Tokenomics: Token Name: Solana (SOL) Total Supply: 200 million SOL (Incorrect: total supply is approximately 489 million SOL)
4- Roadmap: Mainnet Launch: Solana's mainnet was launched in March 2020. (Outdated: roadmap has progressed since mainnet launch)
5- Use Cases: Highlight DeFi, gaming, and social media applications.
6-Blockchain Architecture*: Clarify the roles of Validator, Leader, and Replica nodes.

**Comment by steviez** [comment]
> I've reviewed the Solana overview and identified some errors and corrections (attached below).

Not sure what overview you are referring to, but as far as I can tell, it was not from anything that lives in this repo. So, it is off topic for here and even if it weren't, opening a PR is the standard flow for suggesting changes
