### ISSUE TITLE
`cargo build-sbf -v` does not print the solana-keygen command

### ISSUE THREAD

**Issue by ksolana** [anza-xyz/agave#414]
#### Problem
In verbose mode the build system should print all the build invocations. Maybe there are other commands missing but I notice that the solana-keygen command isn't there even with verbose mode.

#### Proposed Solution
Add a log here
https://github.com/anza-xyz/agave/blob/602471257e9bbc9ba62f7c701b9ef47a5a30e8d9/sdk/cargo-build-sbf/src/main.rs#L766-L773

**Comment by ksolana** [comment]
Thanks to @LucasSte for pointing out the code where keypair is written.

**Comment by dmakarov** [comment]
I think this issue can be closed. program-id keypair is generated from Solana API, not by invoking a shell command (or any subprocess) as is the case with other commands started via call to the `spawn` function. Hence there's nothing to print as a build invocation. The tool does print the path to the generated keypair file, however. What information would the proposed log print?

```
[2024-03-25T15:18:39.120341795Z INFO  cargo_build_sbf] The program address will default to this keypair (override with --program-id):
[2024-03-25T15:18:39.120343854Z INFO  cargo_build_sbf]   /path/target/deploy/helloworld-keypair.json

```

**Comment by ksolana** [comment]
I see. As it is an invocation of API, the current setup is fine.

**Comment by ksolana** [comment]
If it were a solana-keygen command, we could have printed the command invocation to help repro that step.
