### ISSUE TITLE
cargo-build-sbf fails with failed to resolve: use of undeclared crate or module `imp` Error on mac

### ISSUE THREAD

**Issue by whitecometx** [anza-xyz/agave#4149]
#### Problem

I initialized a simple “hello world” cargo project and executed cargo build-sbf and received the following error: (Mac with M3 chip, arm aarch64)

error: failed to parse lock file at: /hello_world/Cargo.lock
Caused by: lock file version 4 requires `-Znext-lockfile-bump`

To circumvent it, I **downgraded cargo.lock** and set it to version = 3 and ran cargo build-sbf and got the below error:

[2024-12-16T19:18:34.729512000Z ERROR cargo_build_sbf] Failed to install platform-tools: Unable to write "/Users/hinakausar/.cache/solana/v1.42/platform-tools/tmp-platform-tools-osx-aarch64.tar.bz2": Custom { kind: Other, error: reqwest::Error { kind: Decode, source: TimedOut } }

To circumvent it, I manually **downloaded platform tools** running the below:

cargo build --target=aarch64-apple-darwin

re-running cargo-build-sbf I now received the following error

error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> src/lib.rs:267:9
    |
267 | /         compile_error!("\
268 | |             target is not supported, for more information see: \
269 | |             https://docs.rs/getrandom/#unsupported-targets\
270 | |         ");
    | |__________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> src/lib.rs:291:5
    |
291 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

How to address the above and Is there a stable version of the tools rustc/solana/ that works without error to be able to execute a simple hello-world program?

####my configuration:
-> solana-cli 2.0.20 (src:20a8749f; feat:607245837, client:Agave)
-> rustc 1.83.0 (90b35a623 2024-11-26)
-> my Cargo.toml is as follows:
```
[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.17.0"
solana-client = "1.18.26"
solana-sdk = "1.18.26"

[lib]
crate-type = ["cdylib", "lib"]
```

-> My lib.rs is as follows:
```
use solana_program::{
    account_info::AccountInfo,
    entrypoint,
    entrypoint::ProgramResult,
    pubkey::Pubkey,
    msg,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    _program_id: &Pubkey,
    _accounts: &[AccountInfo],
    _instruction_data: &[u8]
) -> ProgramResult {
    msg!("Hello, world!");
    Ok(())
}
```

#### Proposed Solution

**Comment by joncinque** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Unless there exists evidence that this is a bug with Solana itself, please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
