### ISSUE TITLE
test-validator: Cloned upgradeable programs don't work

### ISSUE THREAD

**Issue by acheroncrypto** [anza-xyz/agave#436]
### Problem

Interacting with cloned upgradeable programs results in `This program may not be used for executing instructions` error.

This is likely related to the recent removal (https://github.com/solana-labs/solana/pull/34194) and readding (https://github.com/anza-xyz/agave/pull/309) of the `executable` flag because this used to work in `1.17.0`.

#### Reproduction

**Version**: v1.18.8

1. Clone the `spl-token-2022` program:

    ```
    solana-test-validator --clone-upgradeable-program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb --url https://api.mainnet-beta.solana.com
    ```

2. Interact with the program:

    ```
    spl-token create-token --program-id TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
    ```

    Results in error:

    ```
    Creating token BUsVqFX4dLFZiYKggKvF9XcmYgaFsBMNkTJfwiyUwvxL under program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
    Error: Client(Error { request: Some(SendTransaction), kind: RpcError(RpcResponseError { code: -32002, message: "Transaction simulation failed: This program may not be used for executing instructions", data: SendTransactionPreflightFailure(RpcSimulateTransactionResult { err: Some(InvalidProgramForExecution), logs: Some([]), accounts: None, units_consumed: Some(0), return_data: None }) }) })
    ```

### Solution

Not sure if it's the best way but setting the program data account of cloned upgradeable programs to `true` fixes this issue.

This is also what `--upgradeable-program` option (https://github.com/solana-labs/solana/pull/30412) does:

https://github.com/anza-xyz/agave/blob/b2b159ad9204bf7744b78b8aa062636d1646f4af/test-validator/src/lib.rs#L750

**Comment by acheroncrypto** [comment]
After debugging this issue further, I found out that this broke after https://github.com/solana-labs/solana/pull/34407 (not the `executable` flag PRs).

https://github.com/solana-labs/solana/commit/22bfcd92e0f4263c0bd839dde56ab10ecb31c569 is a rather complex commit, so I don't know which part of the commit caused this issue. Fixing this behavior from the `test-validator` side seems to be much simpler if there is no other problems with the mentioned change.

**Comment by buffalojoec** [comment]
@acheroncrypto thanks for reporting and also digging into this!

I've been checking this out as well, and I found so far that this seems to be specific to the "cloning down" action:

- The existing `--upgradeable-program` argument sets the program data account as `executable: true` (as depicted in the issue above). I can invoke this program without issue.
- When modifying the `--upgradeable-program` argument to set the program data account as `executable: false` - as is done by the loader - I can invoke this program without issue.
- When deploying my program to the running local validator, the program data account is set to `executable: false`- as is done by the loader - I can invoke this program without issue. 
- When deploying my program to devnet, then cloning it down using `--clone-upgradeable-program`, I can see the program data account is `executable: false`, and I get the reported issue.

As you've mentioned above, the issue also seems unrelated to the `executable` flag.

I'll continue checking this out.

**Comment by buffalojoec** [comment]
I'm quite surprised we haven't seen this reported yet, but I think I've narrowed it down.

The issue appears to be that the cloned program data account's deployment slot is preserved from the cluster it clones the account from, which is problematic when the programs cache goes to attempt an extraction.

https://github.com/anza-xyz/agave/blob/b01b0d0239d4399154a09273affb7974db252fac/program-runtime/src/loaded_programs.rs#L908

At a high-level, it appears that this causes a continuous loop on Bank's `replenish_program_cache`, which is terminated (quickly) by the `hit_max_limit` check.

https://github.com/anza-xyz/agave/blob/b01b0d0239d4399154a09273affb7974db252fac/runtime/src/bank.rs#L4989-L5002

I intend to get a more descriptive and formal report, and ensure there isn't a deeper runtime issue. However, in the meantime I can assert that simply overwriting a cloned program data account's slot to `0` fixes the issue.
