### ISSUE TITLE
getSignaturesForAddress not returning expected transactions

### ISSUE THREAD

**Issue by fafrd** [anza-xyz/agave#530]
I'm trying to track transfer of the USDY token, `A1KLoBrKBde8Ty9qtNQUtq3C2ortoC3u7twggz7sEto6`. The `getSignaturesForAddress` API is not returning all the results I expect.

For example, this transaction shows up in getSignaturesForAddress:
[3Ho6c6W4CyidzBaGZ9jYnvJZr4uXkWMk88ZDvN4WZd8difKBHgafjn6DNqJ6uW1pNfVBgnMUcmM19F32Dqos6tnA](https://solscan.io/tx/3Ho6c6W4CyidzBaGZ9jYnvJZr4uXkWMk88ZDvN4WZd8difKBHgafjn6DNqJ6uW1pNfVBgnMUcmM19F32Dqos6tnA)

But some transactions do not show, such as this one:
[5jZYVxqLZkaff6G5fYrrbTvTNtPySqRsr5xG6PXRjU9YQrV72mrzF1txNm9GHr3NbjjEswSaqfmzNAVm4yHXqxBa](https://solscan.io/tx/5jZYVxqLZkaff6G5fYrrbTvTNtPySqRsr5xG6PXRjU9YQrV72mrzF1txNm9GHr3NbjjEswSaqfmzNAVm4yHXqxBa)

They're both version 0 transactions. **Both transactions reference the signer's Token Account for USDY in the `accountKeys` list.** As far as I can tell, the main difference here is that the first transaction references the USDY token in the Address Lookup Table, but the second does not. When calling `getTransaction`, I clearly see the USDY token shown in preTokenBalances and postTokenBalances for both txns.

Why might getSignaturesForAddress not show the second txn here, when it clearly interacts with the specified address? Is this a bug?

**Comment by CriesofCarrots** [comment]
We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself. Questions like yours deserve a purpose-built Q&A forum. In future, unless there exists evidence that this is a bug with Solana itself, please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask

However, quickly:

> As far as I can tell, the main difference here is that the first transaction references the USDY token in the Address Lookup Table, but the second does not.

The main difference is that `A1KLoBrKBde8Ty9qtNQUtq3C2ortoC3u7twggz7sEto6` was actually loaded as part of the first transaction, while it is only referenced in the token-balance metadata in the second.

The data store for `getSignaturesForAddress` only indexes addresses that are loaded for processing the transaction, which means they are named either in the `accountKeys` list or one of the `loadedAddresses` lists, from the perspective of `getTransaction`.
While RPC nodes do look up some additional spl-token information (like account mints and owners) to generate and store the token-balance metadata, they do not create signature-for-address entries for these additional addresses.
