### ISSUE TITLE
Incremental snapshot cleanup is not working as expected.

### ISSUE THREAD

**Issue by iammelea** [anza-xyz/agave#580]
Hello, after getting some crash today caused by no space on the device. 
And analyzing why, I see that the files are a little larger and that at the end of the snapshot creation now needs more storage than I can obtain if the incremental folder is cleaned properly. 
Note: This is an error that I have been observing for a long time but I did not give it much importance until today when I have had two crashes.

The validator starts with the arguments

`--maximum-incremental-snapshots-to-retain 2`

then , fter creating the first snapshot or downloading it, the validator will start creating the incremental-snapshots and maintain 2 incremental as expected.

The problem arises when creating the second large snapshot, so instead of keeping only 2 incremental ones, it will keep 3, an old one that will always take up space and is useless because it is old.

The solution is to always keep 2 as expected if that is a startup cmd line option.
Thanks

**Comment by steviez** [comment]
@iammelea - Are you also using `--maximum-full-snapshots-to-retain`, and if so, what value?

**Comment by iammelea** [comment]
> @iammelea - Are you also using `--maximum-full-snapshots-to-retain`, and if so, what value?

Not. This happened on different nodes without that option, just default.

**Comment by steviez** [comment]
Got it. So I think we retain the latest incremental for the older full snapshot as well. For example, here are some snapshots on my system right now. I reordered them to illustrate the point
```
66G snapshot-258905754-7VbYUVFpLoAaXsD18758fqHsBVXgGxmBmv5SMN9JRGFz.tar.zst
 5.1G incremental-snapshot-258905754-258934446-FCtfSbvnq6g86DxBGewo5EDY65dQ4mhoRvtmZKKzda95.tar.zst

66G snapshot-258934562-7WbgusJS2d33NBwahykk3f5QVnReSNQfWirwBm8Aa2AZ.tar.zst
 4.3G incremental-snapshot-258934562-258958514-DR9JuqTcLQeok19MjyksN2dyHekzr9ucgn3u2hamgQyz.tar.zst
 4.3G incremental-snapshot-258934562-258958622-AtZpaFF2Ve8tc1zgvnGyoc163Pa8afHzXkVzCVr4vHez.tar.zst
 4.4G incremental-snapshot-258934562-258958855-6vU8PEmqQCWoCbFHgwkcvNy4kwW7LbFtRc8w4hFsp4Ui.tar.zst
 4.4G incremental-snapshot-258934562-258958965-2vPJcgVYUNuCAUCu6MqZt2GNJnUL1fonjMUHiZTGYYTX.tar.zst
```

This is with default full (2) and incremental (4) snapshots to retain. Can you confirm that the third incremental snapshot you see corresponds to the older full snapshot. Note the slot numbers in the incremental snapshot filename tells you which full snapshot it "is with". For example, the below incremental is at slot `258934446`, but it is based off of the full snapshot at slot `258905754`
```
incremental-snapshot-258905754-258934446-FCtfSbvnq6g86DxBGewo5EDY65dQ4mhoRvtmZKKzda95.tar.zst
```

**Comment by iammelea** [comment]
yes ser, That's my point, that you end up with three incremental snaps and one is totally useless because it's old.
I think the correct way is to keep only two incremental snaps from the last full snap and not 2 +1  if `--maximum-incremental-snapshots-to-retain 2`

**Comment by steviez** [comment]
@brooksprumo - Any thoughts on updating to count the incremental(s) attached to non-newest full? Presumably we could delete the older after we've created incrementals off of a new full

**Comment by diman-io** [comment]
But then what's the point of keeping the previous full snapshots? Essentially, the incremental is part of it, and historically, storage was divided into two files to speed up save operations.

I think we just need to rewrite the help section to state that the number of incremental snapshots in the parameters refers only to the last full snapshot, but for each full snapshot, its highest incremental snapshot is always stored.

**Comment by steviez** [comment]
> But then what's the point of keeping the previous full snapshots?

Suppose we have the following snapshots on disk (this is what things might look like with default of 2 fulls / 4 incrementals / 100 slot interval for incrementals / 25k slot interval for fulls):
```
snapshot-25000-*.zst
incremental-snapshot-25000-49900-*.zstd

snapshot-50000-*.zst
incremental-snapshot-50000-50100-*.zstd
incremental-snapshot-50000-50200-*.zstd
incremental-snapshot-50000-50300-*.zstd
incremental-snapshot-50000-50400-*.zstd
```
Regardless of whether we keep `incremental-snapshot-25000-49900-*.zstd` or not, we still restart from `snapshot-25000-*.zst`. Granted, if we had to fall back to this snapshot because `snapshot-50000-*.zst` was faulty in some way, not having `incremental-snapshot-25000-49900-*.zstd` would mean an extra 24.9k slots to replay at startup.

I don't have too strong an opinion one way or another - I'm guessing the extra couple GB's only hit Melea's radar due to using `tmpfs` for these snaps

**Comment by brooksprumo** [comment]
As folks have already said, yes, we always keep at least incremental snapshot for each full snapshot. I'm inclined to keep that behavior. I agree with @diman-io that we probably should properly document this behavior in the help text.

@iammelea Would setting `--maximum-full-snapshots-to-retain 1` be acceptable for your usecase?

**Comment by iammelea** [comment]
Ok, I see your point. but you understand mine:

`--maximum-incremental-snapshots-to-retain 1`
& default 2 snaps
```
incremental-snapshot-259281301-259310426-7r7oxkk89TewDnRzEe2Y9z3ve3p2sWHP7PchuuyBY6Gq.tar.zst 
incremental-snapshot-259310647-259335150-8c34a1RPiabPfsenyuSJHoE6aZS4LqrcdGsfnjJBxS6J.tar.zst

snapshot-259281301-2pmoUNnjjBu43ivrZkJ7t6xks21AgQJ6PaV7xffsYWTn.tar.zst  
snapshot-259310647-ABuv9SQan4Di9tXgritjHVHUTKmU1J4CCK6gzJLtnM9D.tar.zst
```

It makes sense to keep two snaps and since I want to retain an incremental, to keep 1 incremental for each snap I store.
its fine.

But my issue is related to 
`--maximum-incremental-snapshots-to-retain 2`
& default 2 snaps

```
snapshot-259397734-31w4f7U3DvRsKQMuCwVeyKpWpacXK7ghkHsJ4PrmvtJq.tar.zst  
snapshot-259426579-21LfHrwjrkEWTaTdM8J7y4vWM9HbCbSywE2CJHw7T7jX.tar.zst

incremental-snapshot-259397734-259426336-EML2w54aDBJEewcbdsHtEHbmVex5fVTEFf3kJjBzUQVN.tar.zst  
incremental-snapshot-259426579-259431850-DyBZZt2HYSQ6L8gsHMHyxNy59AngeRSVBG8oRjuEbnmc.tar.zst  
incremental-snapshot-259426579-259431620-5Vec9cAJqxwHPiZAQ8thNuzEDTYmAY2tuX2qbGK7zKpp.tar.zst 
```
because following your logic,  there is one incremental missing for the oldest snap, so you keep 2 incremental for each snap if `--maximum-incremental-snapshots-to-retain 2`

Following this logic, then do not have to delete an incremental, but rather leave one more for the old snap if run with the two options `--maximum-incremental-snapshots-to-retain 2` & default 2 snaps.

think would be the right way. 

But affirmatively I can work with my own configuration to overcome this.
If you think it should stay like this, you can close this.

**Comment by brooksprumo** [comment]
I don't think we need to keep `max-incr-snaps` *per* full snapshot, but I do see how that would be a possible way to interpret the `--maximum-incremental-snapshots-to-retain` arg.

The retain-one-incr-snap-per-old-full-snap is a bit strange, I agree. I think I lean towards having the `--maximum-incremental-snapshots-to-retain` arg apply to all the incremental snapshots, so older full snapshots would *not* always keep an incremental snapshot too.

Previously we used to purge all incremental snapshots for older full snapshots. That behavior was changed by https://github.com/solana-labs/solana/pull/24837 to the current behavior. If the number of incr snaps to retain is regardless of full snapshots, I think the original problem addressed in the PR may no longer be guaranteed to fixed though. Maybe that original problem is no longer an issue? With 2-4 incr snaps to retain, assuming the main node crashed and the backup node was checked for snapshots fast enough, then yes, we'd still be good. If we wait too long, the backup node will have created new incr snaps only for the new full snap, and thus purged the incr snaps for the old full snap. However, if we wait too long, the main node may be too far behind anyway, so this may all be moot.

I'm leaning towards `--maximum-incremental-snapshots-to-retain` applies overall, to all the incremental snapshots. So for example, with a max-to-retain of 4, we could have 1 on the newest full snap, and 3 on the next older full snap.

@mvines Do you have any thoughts here?

**Comment by iammelea** [comment]
closing this, meanwhile related to this.
https://github.com/anza-xyz/agave/issues/1563

**Comment by iammelea** [comment]
closing this, meanwhile related to this.
https://github.com/anza-xyz/agave/issues/1563
