### ISSUE TITLE
Solana Frontend connection issue for making the transactions

### ISSUE THREAD

**Issue by blockchain-app12** [anza-xyz/agave#87]
We working for a dex based solution on solana network, it properly works on localnet including all the trasanctions. But we make changes to devnet remaining all same but encountering the following issues. Please let me know, whether devnet has any issues or any other solutions needed to resolve this case.

![image](https://github.com/anza-xyz/agave/assets/48212011/6a2088d5-bb15-4628-9e51-f2a25160764b)

**Comment by Nagaprasadvr** [comment]
From the error it doesn't look like connection issue !
We need more logs here , can u use try , catch and console the error! Also if u could add which instruction u are using here that would be great!

**Comment by CriesofCarrots** [comment]
@blockchain-app12 , we don't offer app-development support in this repo. I think your best bet would be [Solana Stack Exchange](https://solana.stackexchange.com/). You can ask questions about the public clusters, like devnet, there as well.
If you discover a bug in the actual validator software, then please open a new issue here.

**Comment by blockchain-app12** [comment]
Hi Team, 
Hereby sharing the set of codes and console of the error log, please clarify it will more helpful. I working all of the scenarios and modules, it is perfectly working in solana localnet with the Frontend, while we change the network to devnet, the following errors occurs when try to connect the phantom wallet with the functions.

![image](https://github.com/anza-xyz/agave/assets/48212011/56cc77b0-1fae-4533-a275-df02120531fd)

Error console log snap : 

![image](https://github.com/anza-xyz/agave/assets/48212011/92dd6914-c6ed-46fc-9ec8-551bee0002b2)

**Comment by blockchain-app12** [comment]
Please let me know the possibilities for the above shared on the solana.
