### ISSUE TITLE
Unable to Retrieve Transaction with get_transaction Function

### ISSUE THREAD

**Issue by Chall-T** [anza-xyz/agave#919]
#### Problem
When attempting to retrieve a transaction using the get_transaction function, I encountered the following error:

`Err(Error { request: Some(GetTransaction), kind: RpcError(RpcResponseError { code: -32015, message: "Transaction version (0) is not supported by the requesting client. Please try the request again with the following configuration parameter: \"maxSupportedTransactionVersion\": 0", data: Empty }) })
`

The issue is that in the library I can not add `"maxSupportedTransactionVersion": 0` in the params.

**Comment by orsenkucher** [comment]
That bot action and closing without any review is fucked up

**Comment by orsenkucher** [comment]
@steviez maybe you can address the issue actually, or point to the resource with solution?

**Comment by steviez** [comment]
> That bot action and closing without any review is fucked up

I disagree; the message pretty clearly states why we don't accept questions of this nature on GitHub.

> [@steviez](https://github.com/steviez) maybe you can address the issue actually, or point to the resource with solution?

Have you tried searching the error message online ? Doing so just now, I see several results that provide good information with a couple minutes of reading.
